<?php
$labels['acc_acc'] = 'Акаунт';
$labels['acc_alias'] = 'Свързани имейл адрес(и)';
$labels['acc_general'] = 'Информация за акаунта';
$labels['acc_pass'] = 'Промяна на парола';
$labels['acc_forward'] = 'Пренасочване';
$labels['acc_fetchmail'] = 'Външни POP3/IMAP пощи';
$labels['acc_autoreply'] = 'Автоматичен отговор';
$labels['acc_filter'] = 'Филтри';
$labels['acc_spam'] = 'Спам защита';
$labels['acc_wblist'] = 'Черен/Бял списък';
$labels['acc_lastlogin'] = 'Последен вход';
$labels['acc_defaultidentity'] = 'Основна самоличност';
$labels['acc_noalias'] = 'Няма свързани имейл адрес(и)';