<?php
$labels['acc_acc'] = 'Nastavení e-mail účtu';
$labels['acc_alias'] = 'E-mail alias(y)';
$labels['acc_general'] = 'Informace o e-mail účtu uživatele';
$labels['acc_pass'] = 'Změna hesla';
$labels['acc_forward'] = 'Přeposílání e-mailů';
$labels['acc_fetchmail'] = 'Externí získávání e-mailů';
$labels['acc_autoreply'] = 'Automatická odpověď';
$labels['acc_filter'] = 'Mailový filtr';
$labels['acc_spam'] = 'Ochrana proti spamu';
$labels['acc_wblist'] = 'Černá/Bílá listina';
$labels['acc_lastlogin'] = 'Poslední přihlášení';
$labels['acc_defaultidentity'] = 'Hlavní e-mail';
$labels['acc_noalias'] = 'Žádné e-mail alias(y)';