<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Linkede e-mailadresser';
$labels['acc_general'] = 'Generelt';
$labels['acc_pass'] = 'Adgangskode';
$labels['acc_forward'] = 'Videresendelse';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Autosvar';
$labels['acc_filter'] = 'Mailfilter';
$labels['acc_wblist'] = 'Sort/Hvid-liste';
$labels['acc_lastlogin'] = 'Seneste login';
$labels['acc_defaultidentity'] = 'Standardidentitet';
$labels['acc_noalias'] = 'Ingen linkede e-mailadresser';
?>
