<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Verkn&uuml;pfte Emailadresse(n)';
$labels['acc_general'] = 'Allgemein';
$labels['acc_pass'] = 'Passwort';
$labels['acc_forward'] = 'Weiterleitung';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Automatische Nachricht';
$labels['acc_filter'] = 'Mail Filter';
$labels['acc_wblist'] = 'Schwarz/Weiß Liste';
$labels['acc_lastlogin'] = 'Letztes Login';
$labels['acc_defaultidentity'] = 'Standard-Absender';
$labels['acc_noalias'] = 'Keine Verkn&uuml;pfte Emailadresse vorhanden';
?>