<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Verknüpfte E-Mail-Adresse(n)';
$labels['acc_general'] = 'Allgemein';
$labels['acc_pass'] = 'Passwort ändern';
$labels['acc_forward'] = 'Weiterleitung';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Automatische Antwort';
$labels['acc_filter'] = 'Filterregeln';
$labels['acc_spam'] = 'Spamschutz';
$labels['acc_wblist'] = 'Blacklist/Whitelist';
$labels['acc_lastlogin'] = 'Letzter Login';
$labels['acc_defaultidentity'] = 'Standard-Absender';
$labels['acc_noalias'] = 'Keine verknüpfte E-Mail-Adresse vorhanden';