<?php
$labels['acc_acc'] = 'Account';
$labels['acc_alias'] = 'Linked email address(es)';
$labels['acc_general'] = 'General';
$labels['acc_pass'] = 'Password';
$labels['acc_forward'] = 'Forwarding';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Autoreply';
$labels['acc_filter'] = 'Mail Filter';
$labels['acc_wblist'] = 'Black/White List';
$labels['acc_lastlogin'] = 'Last Login';
$labels['acc_defaultidentity'] = 'Default Identity';
$labels['acc_noalias'] = 'No linked email address(es)';
?>