<?php
$labels['isp_acc'] = 'Account';
$labels['isp_alias'] = 'Linked email address(es)';
$labels['isp_general'] = 'General';
$labels['isp_pass'] = 'Password';
$labels['isp_forward'] = 'Forwarding';
$labels['isp_fetchmail'] = 'Fetchmail';
$labels['isp_autoreply'] = 'Autoreply';
$labels['isp_filter'] = 'Mail Filter';
$labels['lastlogin'] = 'Last Login';
$labels['defaultidentity'] = 'Default Identity';
$labels['noalias'] = 'No linked email address(es)';
?>