<?php
$labels['acc_acc'] = 'Account';
$labels['acc_alias'] = 'Linked email address(es)';
$labels['acc_general'] = 'General';
$labels['acc_pass'] = 'Change password';
$labels['acc_forward'] = 'Forwarding';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Autoreply';
$labels['acc_filter'] = 'Filter rules';
$labels['acc_spam'] = 'Spam protection';
$labels['acc_wblist'] = 'Blacklist / Whitelist';
$labels['acc_lastlogin'] = 'Last login';
$labels['acc_defaultidentity'] = 'Default sender';
$labels['acc_noalias'] = 'No linked email address(es)';