<?php
$labels['isp_acc'] = 'Cuenta';
$labels['isp_alias'] = 'Cuentas de correo ligadas a';
$labels['isp_general'] = 'General';
$labels['isp_pass'] = 'Contrase&ntilde;a';
$labels['isp_forward'] = 'Reenvio';
$labels['isp_fetchmail'] = 'Correo Externo';
$labels['isp_autoreply'] = 'Autorespuesta';
$labels['isp_filter'] = 'Filtros de Correo';
$labels['lastlogin'] = 'Ultima Sesi&oacute;n';
$labels['defaultidentity'] = 'Identidad Predeterminada';
$labels['noalias'] = 'No tiene cuentas de correo ligadas';
?>