<?php
$labels['acc_acc'] = 'Cuenta';
$labels['acc_alias'] = 'Cuentas de correo ligadas a';
$labels['acc_general'] = 'General';
$labels['acc_pass'] = 'Cambiar la contraseña';
$labels['acc_forward'] = 'Reenvio';
$labels['acc_fetchmail'] = 'Cuentas externas';
$labels['acc_autoreply'] = 'Respuesta automática';
$labels['acc_filter'] = 'Filtros de correo';
$labels['acc_spam'] = 'Protección contra spam';
$labels['acc_wblist'] = 'Lista blanca y negra';
$labels['acc_lastlogin'] = 'Última sesión';
$labels['acc_defaultidentity'] = 'Identidad predeterminada';
$labels['acc_noalias'] = 'No tiene cuentas de correo ligadas';