<?php
$labels['acc_acc'] = 'Cuenta';
$labels['acc_alias'] = 'Cuentas de correo ligadas a';
$labels['acc_general'] = 'General';
$labels['acc_pass'] = 'Contrase&ntilde;a';
$labels['acc_forward'] = 'Reenvio';
$labels['acc_fetchmail'] = 'Correo Externo';
$labels['acc_autoreply'] = 'Autorespuesta';
$labels['acc_filter'] = 'Filtros de Correo';
$labels['acc_wblist'] = 'Black/White List';
$labels['acc_lastlogin'] = 'Ultima Sesi&oacute;n';
$labels['acc_defaultidentity'] = 'Identidad Predeterminada';
$labels['acc_noalias'] = 'No tiene cuentas de correo ligadas';
?>