<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Ühendatud kontod';
$labels['acc_general'] = 'Üldine';
$labels['acc_pass'] = 'Salasõna';
$labels['acc_forward'] = 'Suunamine';
$labels['acc_fetchmail'] = 'Hankija';
$labels['acc_autoreply'] = 'Automaatvastus';
$labels['acc_filter'] = 'Filter';
$labels['acc_spam'] = 'Rämpsposti kaitse';
$labels['acc_wblist'] = 'Must/Valge nimekiri';
$labels['acc_lastlogin'] = 'Viimati külastas';
$labels['acc_defaultidentity'] = 'Vaike identiteet';
$labels['acc_noalias'] = 'Puuduvad ühendatud kontod';