<?php
$labels['acc_acc'] = 'Tili';
$labels['acc_alias'] = 'Liitetyt sähköpostiosoitteet';
$labels['acc_general'] = 'Tietoja';
$labels['acc_pass'] = 'Vaihda salasana';
$labels['acc_forward'] = 'Edelleenlähetys';
$labels['acc_fetchmail'] = 'Postin nouto';
$labels['acc_autoreply'] = 'Lomavastaaja';
$labels['acc_filter'] = 'Suodatinasetukset';
$labels['acc_spam'] = 'Roskapostisuojaus';
$labels['acc_wblist'] = 'Blacklist / Whitelist';
$labels['acc_lastlogin'] = 'Edellinen kirjautuminen';
$labels['acc_defaultidentity'] = 'Oletuslähettäjä';
$labels['acc_noalias'] = 'Ei liitettyjä sähköpostiosoitteita';
