<?php
$labels['isp_acc'] = 'Compte';
$labels['isp_alias'] = 'Adresse(s) email(s) liée(s)';
$labels['isp_general'] = 'Général';
$labels['isp_pass'] = 'Mot de passe';
$labels['isp_forward'] = 'Transfert';
$labels['isp_fetchmail'] = 'Récupération de compte';
$labels['isp_autoreply'] = 'Réponse automatique';
$labels['isp_filter'] = 'Filtrage des mails';
$labels['lastlogin'] = 'Dernière connexion';
$labels['defaultidentity'] = 'Identité par défaut';
$labels['noalias'] = 'Aucune adresse email liée';
?>
