<?php
$labels['acc_acc'] = 'Compte';
$labels['acc_alias'] = 'Adresse(s) email(s) liée(s)';
$labels['acc_general'] = 'Général';
$labels['acc_pass'] = 'Changer le mot de passe';
$labels['acc_forward'] = 'Transfert';
$labels['acc_fetchmail'] = 'Récupération de compte';
$labels['acc_autoreply'] = 'Réponse automatique';
$labels['acc_filter'] = 'Filtrage des mails';
$labels['acc_spam'] = 'Protection anti-spam';
$labels['acc_wblist'] = 'Liste Noire/Blanche';
$labels['acc_lastlogin'] = 'Dernière connexion';
$labels['acc_defaultidentity'] = 'Identité par défaut';
$labels['acc_noalias'] = 'Aucune adresse email liée';