<?php
$labels['acc_acc'] = 'Conta';
$labels['acc_alias'] = 'Contas de correo ligadas a';
$labels['acc_general'] = 'Xeral';
$labels['acc_pass'] = 'Cambiar o contrasinal';
$labels['acc_forward'] = 'Reenvío';
$labels['acc_fetchmail'] = 'Contas externas';
$labels['acc_autoreply'] = 'Resposta automática';
$labels['acc_filter'] = 'Filtros de correo';
$labels['acc_spam'] = 'Protección contra spam';
$labels['acc_wblist'] = 'Listas branca e negra';
$labels['acc_lastlogin'] = 'Última sesión';
$labels['acc_defaultidentity'] = 'Identidade predeterminada';
$labels['acc_noalias'] = 'Non ten contas de correo ligadas';