<?php
$labels['acc_acc'] = 'Profil';
$labels['acc_alias'] = 'Linkelt email címek';
$labels['acc_general'] = 'Általános';
$labels['acc_pass'] = 'Jelszó megváltoztatása';
$labels['acc_forward'] = 'Továbbítás';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Automatikus válasz';
$labels['acc_filter'] = 'Levél szűrő';
$labels['acc_spam'] = 'Spam-védelem';
$labels['acc_wblist'] = 'Black/White listák';
$labels['acc_lastlogin'] = 'Utolsó bejelentkezés';
$labels['acc_defaultidentity'] = 'Alapértelmezett azonosító';
$labels['acc_noalias'] = 'Nincsenek linkelt email címek';