<?php
$labels['isp_acc'] = 'Account';
$labels['isp_alias'] = 'Indirizzi email associati (alias)';
$labels['isp_general'] = 'Generale';
$labels['isp_pass'] = 'Password';
$labels['isp_forward'] = 'Inoltro';
$labels['isp_fetchmail'] = 'Recupero posta';
$labels['isp_autoreply'] = 'Autoreply';
$labels['isp_filter'] = 'Filtri posta';
$labels['lastlogin'] = 'Ultimo accesso';
$labels['defaultidentity'] = 'Identità predefinita';
$labels['noalias'] = 'Nessun alias definito';
?>