<?php
$labels['acc_acc'] = 'Account';
$labels['acc_alias'] = 'Indirizzi email associati (alias)';
$labels['acc_general'] = 'Generale';
$labels['acc_pass'] = 'Password';
$labels['acc_forward'] = 'Inoltro';
$labels['acc_fetchmail'] = 'Recupero posta';
$labels['acc_autoreply'] = 'Autoreply';
$labels['acc_filter'] = 'Filtri posta';
$labels['acc_wblist'] = 'White/Black List';
$labels['acc_lastlogin'] = 'Ultimo accesso';
$labels['acc_defaultidentity'] = 'Identità predefinita';
$labels['acc_noalias'] = 'Nessun alias definito';
?>