<?php
$labels['acc_acc'] = 'Account';
$labels['acc_alias'] = 'Indirizzi email associati (alias)';
$labels['acc_general'] = 'Generale';
$labels['acc_pass'] = 'Cambiare la password';
$labels['acc_forward'] = 'Inoltro';
$labels['acc_fetchmail'] = 'Recupero posta';
$labels['acc_autoreply'] = 'Autoreply';
$labels['acc_filter'] = 'Filtri posta';
$labels['acc_spam'] = 'Protezione da spam';
$labels['acc_wblist'] = 'Lista nera/bianca';
$labels['acc_lastlogin'] = 'Ultimo accesso';
$labels['acc_defaultidentity'] = 'Identità predefinita';
$labels['acc_noalias'] = 'Nessun alias definito';