<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Verbonnen E-Mail-Adress(en)';
$labels['acc_general'] = 'Allgemeng';
$labels['acc_pass'] = 'Passwuert änneren';
$labels['acc_forward'] = 'Weiderleedung';
$labels['acc_fetchmail'] = 'Extern E-Mailen ofruffen';
$labels['acc_autoreply'] = 'Automatesch Äntwert';
$labels['acc_filter'] = 'E-Mail-Filter';
$labels['acc_spam'] = 'Spamschutz';
$labels['acc_wblist'] = 'Schwaarz/Wäiss Lëscht';
$labels['acc_lastlogin'] = 'Leschte Login';
$labels['acc_defaultidentity'] = 'Standard-Identitéit';
$labels['acc_noalias'] = 'Keng verbonnen E-Mail-Adress fonnt';