<?php
$labels['acc_acc'] = 'Konta pārvaldība';
$labels['acc_alias'] = 'Saistītā(-ās) e-pasta adrese(-es)';
$labels['acc_general'] = 'Pamatinformācija';
$labels['acc_pass'] = 'Paroles maiņa';
$labels['acc_forward'] = 'E-pasta pārsūtīšana';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'E-pasta automātiskās atbildes';
$labels['acc_filter'] = 'Filtrēšanas nosacījumi';
$labels['acc_spam'] = 'Aizsardzība pret surogātpastu';
$labels['acc_wblist'] = 'Melnais saraksts / baltais saraksts';
$labels['acc_lastlogin'] = 'Pēdējā pieteikšanās';
$labels['acc_defaultidentity'] = 'Nosūtītājs';
$labels['acc_noalias'] = 'Nav saistītas e-pasta adreses';
