<?php
$labels['acc_acc'] = 'Account';
$labels['acc_alias'] = 'Verbonden e-mailadressen';
$labels['acc_general'] = 'Algemeen';
$labels['acc_pass'] = 'Wachtwoord wijzigen';
$labels['acc_forward'] = 'Doorsturen';
$labels['acc_fetchmail'] = 'Extern mailaccount';
$labels['acc_autoreply'] = 'Autobeantwoorden';
$labels['acc_filter'] = 'Filter regels';
$labels['acc_spam'] = 'Spambeveiliging';
$labels['acc_wblist'] = 'White/Black List';
$labels['acc_lastlogin'] = 'Laatste keer ingelogd:';
$labels['acc_defaultidentity'] = 'Standaard identiteit';
$labels['acc_noalias'] = 'Geen e-mailadressen verbonden';