<?php
$labels['isp_acc'] = 'Account';
$labels['isp_alias'] = 'Verbonden e-mailadressen';
$labels['isp_general'] = 'Algemeen';
$labels['isp_pass'] = 'Wachtwoord';
$labels['isp_forward'] = 'Doorsturen';
$labels['isp_fetchmail'] = 'Fetchmail';
$labels['isp_autoreply'] = 'Autobeantwoorden';
$labels['isp_filter'] = 'Mail Filter';
$labels['lastlogin'] = 'Laatste keer ingelogd:';
$labels['defaultidentity'] = 'Standaard identiteit';
$labels['noalias'] = 'Geen e-mailadressen verbonden';
?>