<?php
$labels['isp_acc'] = 'Konto';
$labels['isp_alias'] = 'Powiazane adresy email';
$labels['isp_general'] = 'Ogólne';
$labels['isp_pass'] = 'Haslo';
$labels['isp_forward'] = 'Przekazywanie poczty';
$labels['isp_fetchmail'] = 'Pobieranie poczty';
$labels['isp_autoreply'] = 'Autoodpowiedz';
$labels['isp_filter'] = 'Filtr poczty';
$labels['lastlogin'] = 'Ostatnio zalogowany';
$labels['defaultidentity'] = 'Domyslna tozsamosc';
$labels['noalias'] = 'Brak powiazanych adresów email';
?> 