<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Powiązane adresy email';
$labels['acc_general'] = 'Ogólne';
$labels['acc_pass'] = 'Zmiana hasła';
$labels['acc_forward'] = 'Przekazywanie poczty';
$labels['acc_fetchmail'] = 'Pobieranie poczty';
$labels['acc_autoreply'] = 'Autoodpowiedź';
$labels['acc_filter'] = 'Filtr poczty';
$labels['acc_spam'] = 'Ochrona przed spamem';
$labels['acc_wblist'] = 'Czarna/Biała lista';
$labels['acc_lastlogin'] = 'Ostatnio zalogowany';
$labels['acc_defaultidentity'] = 'Domyślna tożsamość';
$labels['acc_noalias'] = 'Brak powiązanych adresów email';