<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Powiazane adresy email';
$labels['acc_general'] = 'Ogólne';
$labels['acc_pass'] = 'Haslo';
$labels['acc_forward'] = 'Przekazywanie poczty';
$labels['acc_fetchmail'] = 'Pobieranie poczty';
$labels['acc_autoreply'] = 'Autoodpowiedz';
$labels['acc_filter'] = 'Filtr poczty';
$labels['acc_wblist'] = 'White/Black List';
$labels['acc_lastlogin'] = 'Ostatnio zalogowany';
$labels['acc_defaultidentity'] = 'Domyslna tozsamosc';
$labels['acc_noalias'] = 'Brak powiazanych adresów email';
?> 