<?php
$labels['acc_acc'] = 'Conta';
$labels['acc_alias'] = 'Endereços de Correio Lincados';
$labels['acc_general'] = 'Geral';
$labels['acc_pass'] = 'Mudar senha';
$labels['acc_forward'] = 'Encaminhamento';
$labels['acc_autoreply'] = 'Autoresponder';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_filter'] = 'Filtro de Correio';
$labels['acc_spam'] = 'Proteção contra Spam';
$labels['acc_wblist'] = 'Lista negra e branca';
$labels['acc_lastlogin'] = 'Último Login';
$labels['acc_defaultidentity'] = 'Identidade Padrão';
$labels['acc_noalias'] = 'Endereços de correio não lincados';