<?php
$labels['isp_acc'] = 'Conta';
$labels['isp_alias'] = 'Endereços de Correio Lincados';
$labels['isp_general'] = 'Geral';
$labels['isp_pass'] = 'Senha';
$labels['isp_forward'] = 'Encaminhamento';
$labels['isp_autoreply'] = 'Autoresponder';
$labels['isp_fetchmail'] = 'Fetchmail';
$labels['isp_filter'] = 'Filtro de Correio';
$labels['lastlogin'] = 'Último Login';
$labels['defaultidentity'] = 'Identidade Padrão';
$labels['noalias'] = 'Endereços de correio não lincados';
?>