<?php
$labels['acc_acc'] = 'Учетная запись';
$labels['acc_alias'] = 'Адреса электронной почты';
$labels['acc_general'] = 'Общее';
$labels['acc_pass'] = 'Изменить пароль';
$labels['acc_forward'] = 'Пересылка почты';
$labels['acc_fetchmail'] = 'Сборка почты';
$labels['acc_autoreply'] = 'Автоответ';
$labels['acc_filter'] = 'Почтовые фильтры';
$labels['acc_spam'] = 'Защита от спама';
$labels['acc_wblist'] = 'Чёрные/Белые списки';
$labels['acc_lastlogin'] = 'Последний вход';
$labels['acc_defaultidentity'] = 'Отправитель по-умолчанию';
$labels['acc_noalias'] = 'Нет связанных адресов электронной почты';