<?php
$labels['acc_acc'] = 'учетная запись';
$labels['acc_alias'] = 'алиас';
$labels['acc_general'] = 'общее';
$labels['acc_pass'] = 'пароль';
$labels['acc_forward'] = 'пересылка';
$labels['acc_fetchmail'] = 'сборка почты';
$labels['acc_autoreply'] = 'автоответ';
$labels['acc_filter'] = 'фильтр';
$labels['lastlogin'] = 'прошлый раз в системе';
$labels['defaultidentity'] = 'отправитель по умолчанию';
$labels['noalias'] = 'алиаса не существует';
?>