<?php
$labels['acc_acc'] = 'Nastavenia e-mail účtu';
$labels['acc_alias'] = 'E-mail alias(y)';
$labels['acc_general'] = 'Informácie o e-mail účte používateľa';
$labels['acc_pass'] = 'Zmena hesla';
$labels['acc_forward'] = 'Preposielanie e-mailov';
$labels['acc_fetchmail'] = 'Preberanie e-mailov';
$labels['acc_autoreply'] = 'Automatická odpoveď';
$labels['acc_filter'] = 'Mailový filter';
$labels['acc_spam'] = 'Ochrana proti spamu';
$labels['acc_wblist'] = 'Čierna/Biela listina';
$labels['acc_lastlogin'] = 'Posledné prihlásenie';
$labels['acc_defaultidentity'] = 'Hlavný e-mail';
$labels['acc_noalias'] = 'Žiadne e-mail alias(y)';
