<?php
$labels['acc_acc'] = 'Račun';
$labels['acc_alias'] = 'Povezani e-poštni naslov(i)';
$labels['acc_general'] = 'Splošno';
$labels['acc_pass'] = 'Sprememba gesla';
$labels['acc_forward'] = 'Posredovanje';
$labels['acc_fetchmail'] = 'Pograbi pošto';
$labels['acc_autoreply'] = 'Odzivnik';
$labels['acc_filter'] = 'Filter pošte';
$labels['acc_spam'] = 'Zaščita pred neželeno pošto';
$labels['acc_wblist'] = 'Bela-črna lista';
$labels['acc_lastlogin'] = 'Zadnja prijava';
$labels['acc_defaultidentity'] = 'Privzeta identiteta';
$labels['acc_noalias'] = 'Ni povezanih e-poštnih naslovov';