<?php
$labels['isp_acc'] = 'Račun';
$labels['isp_alias'] = 'Povezani e-poštni naslov(i)';
$labels['isp_general'] = 'Splošno';
$labels['isp_pass'] = 'Sprememba gesla';
$labels['isp_forward'] = 'Posredovanje';
$labels['isp_fetchmail'] = 'Pograbi pošto';
$labels['isp_autoreply'] = 'Odzivnik';
$labels['isp_filter'] = 'Filter pošte';
$labels['lastlogin'] = 'Zadnja prijava';
$labels['defaultidentity'] = 'Privzeta identiteta';
$labels['noalias'] = 'Ni povezanih e-poštnih naslovov';
?>