<?php
$labels['isp_acc'] = 'Konto';
$labels['isp_alias'] = 'L&auml;nkade mailkonton';
$labels['isp_general'] = 'Generellt';
$labels['isp_pass'] = 'L&ouml;senord';
$labels['isp_forward'] = 'Vidarebefodring';
$labels['isp_fetchmail'] = 'Extern mailserver';
$labels['isp_autoreply'] = 'Autosvar';
$labels['isp_filter'] = 'Mailfilter';
$labels['lastlogin'] = 'Senast inloggad';
$labels['defaultidentity'] = 'Standardidentitet';
$labels['noalias'] = 'Inga l&auml;nkade mailadresser';
?>
