<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Alias f&ouml;r detta konto';
$labels['acc_general'] = 'Generellt';
$labels['acc_pass'] = 'L&ouml;senord';
$labels['acc_forward'] = 'Vidarebefodring';
$labels['acc_fetchmail'] = 'Extern mailserver';
$labels['acc_autoreply'] = 'Autosvar';
$labels['acc_filter'] = 'Mailfilter';
$labels['acc_wblist'] = 'Till&aring;t/sp&auml;rra e-postadresser';
$labels['acc_lastlogin'] = 'Senast inloggad';
$labels['acc_defaultidentity'] = 'Standardidentitet';
$labels['acc_noalias'] = 'Inga alias';
?>
