<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Alias för detta konto';
$labels['acc_general'] = 'Generellt';
$labels['acc_pass'] = 'Ändra lösenord';
$labels['acc_forward'] = 'Vidarebefodring';
$labels['acc_fetchmail'] = 'Extern mailserver';
$labels['acc_autoreply'] = 'Autosvar';
$labels['acc_filter'] = 'Mailfilter';
$labels['acc_spam'] = 'Spamskydd';
$labels['acc_wblist'] = 'Tillåt/spärra e-postadresser';
$labels['acc_lastlogin'] = 'Senast inloggad';
$labels['acc_defaultidentity'] = 'Standardidentitet';
$labels['acc_noalias'] = 'Inga alias';