<?php
$labels['acc_acc'] = 'Hesap';
$labels['acc_alias'] = 'Bağlı E-Posta adres(ler)i';
$labels['acc_general'] = 'Genel';
$labels['acc_pass'] = 'Parola';
$labels['acc_forward'] = 'Yönlendirme';
$labels['acc_fetchmail'] = 'Mail Alma';
$labels['acc_autoreply'] = 'Otomatik Yanıt';
$labels['acc_filter'] = 'Posta Filtresi';
$labels['acc_wblist'] = 'Kara/Beyaz Liste';
$labels['acc_lastlogin'] = 'Son Giriş Zamanı';
$labels['acc_defaultidentity'] = 'Varsayılan Kimlik';
$labels['acc_noalias'] = 'Bağlı E-Posta adres(ler)i bulunamadı';
