<?php
$labels['acc_acc'] = 'Обліковий запис';
$labels['acc_alias'] = 'Додаткові адреси';
$labels['acc_general'] = 'Загальнe';
$labels['acc_pass'] = 'Змінити пароль';
$labels['acc_forward'] = 'Пересилання';
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['acc_autoreply'] = 'Автовідповідач';
$labels['acc_filter'] = 'Фільтри пошти';
$labels['acc_spam'] = 'Захист від спаму';
$labels['acc_wblist'] = 'Чорний/Білий список';
$labels['acc_lastlogin'] = 'Останній логін';
$labels['acc_defaultidentity'] = 'Стандартний відправник';
$labels['acc_noalias'] = 'Немає пов\'язаних електронних адрес';