<?php
$labels['acc_fetchmail'] = 'Външни POP3/IMAP пощи';
$labels['fetchmailtyp'] = 'Протокол';
$labels['fetchmailserver'] = 'POP3/IMAP Сървър';
$labels['fetchmaildelete'] = 'Итриване на писмата след изтегляне';
$labels['fetchmailenabled'] = 'Активна';
$labels['fetchmaildisabled'] = 'неактивна';
$labels['nofetch'] = 'Все още няма добавени записи';
$labels['fetchmail_entries'] = 'Добавени акаунти';
$messages['fetchmaildelconfirm'] = 'Да изтрия ли този запис?';
$messages['fetchmaillimitreached'] = 'Достигнат лимит';
$messages['textempty'] = 'Едно или повече полета са празни. Попълнете ги.';