<?php
$labels = array();
$labels['acc_fetchmail'] = 'Externí získávání e-mailů';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Smazat e-maily po obdržení';
$labels['fetchmailenabled'] = 'Aktivní';
$labels['nofetch'] = 'Nejsou k dispozici žádné záznamy';
$labels['fetchmail_entries'] = 'Již nastavené externí získávání e-mailů';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Jste si jisti, že se má odstranit toto externí získávání e-mailů ?';
$messages['fetchmaillimitreached'] = 'Byl dosažen max. povolený počet externího získávání e-mailů';
$messages['textempty'] = 'Jedno nebo více polí jsou prázdné';
?>