<?php
$labels = array();
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Type';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Slet e-mails efter modtagelse';
$labels['fetchmailenabled'] = 'Aktiveret';
$labels['nofetch'] = 'Ingen poster til rådighed';
$labels['fetchmail_entries'] = 'Tilgængelige poster';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Vil du slette denne post?';
$messages['fetchmaillimitreached'] = 'Begrænsning nået';
$messages['textempty'] = 'Et eller flere felter er tomme';
?>
