<?php
$labels = array();
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Mails nach Empfang l&ouml;schen';
$labels['fetchmailenabled'] = 'Aktivieren';
$labels['nofetch'] = 'Keine Eintr&auml;ge vorhanden';
$labels['fetchmail_entries'] = 'Vorhandene Eintr&auml;ge';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich l&ouml;schen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
$messages['textempty'] = 'Ein oder mehr Felder sind leer';
?>