<?php
$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Mails nach Empfang l&ouml;schen';
$labels['fetchmailenabled'] = 'Aktivieren';
$labels['nofetch'] = 'Keine Eintr&auml;ge vorhanden';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich l&ouml;schen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
?>