<?php
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP-Server';
$labels['fetchmaildelete'] = 'E-Mails nach Empfang löschen';
$labels['fetchmailenabled'] = 'Aktiviert';
$labels['fetchmaildisabled'] = 'Deaktiviert';
$labels['nofetch'] = 'Keine Einträge vorhanden';
$labels['fetchmail_entries'] = 'Vorhandene Einträge';
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
$messages['textempty'] = 'Eines oder mehrere Felder sind leer';