<?php
$labels = array();
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Delete emails after receiving';
$labels['fetchmailenabled'] = 'Enable';
$labels['nofetch'] = 'No entries available';
$labels['fetchmail_entries'] = 'Available entries';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Do you want to delete this entry?';
$messages['fetchmaillimitreached'] = 'Limit reached';
$messages['textempty'] = 'One or more fields are empty';
?>