<?php
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Type';
$labels['fetchmailserver'] = 'POP3/IMAP server';
$labels['fetchmaildelete'] = 'Delete fetched emails remotely';
$labels['fetchmailenabled'] = 'Enabled';
$labels['fetchmaildisabled'] = 'Disabled';
$labels['nofetch'] = 'No entries available';
$labels['fetchmail_entries'] = 'Available entries';
$messages['fetchmaildelconfirm'] = 'Are you sure you want to delete this entry?';
$messages['fetchmaillimitreached'] = 'Limit reached';
$messages['textempty'] = 'One or more fields are empty';