<?php
$labels = array();
$labels['acc_fetchmail'] = 'Cuentas Externas';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Servidor POP3/IMAP';
$labels['fetchmaildelete'] = 'Borrar mensajes del servidor después de recibidos';
$labels['fetchmailenabled'] = 'Activo';
$labels['nofetch'] = 'No se han configurado ninguna cuenta';
$labels['fetchmail_entries'] = 'Cuentas configuradas';

$messages = array();
$messages['fetchmaildelconfirm'] = '¿Seguro que desea borrar esta cuenta?';
$messages['fetchmaillimitreached'] = 'No se pueden añadir más cuentas';
$messages['textempty'] = 'Es necesario cubrir todos los campos';
?>