<?php
$labels = array();
$labels['fetchmail'] = 'Correo Externo';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Servidor POP3/IMAP';
$labels['fetchmaildelete'] = 'Borrar mensajes despu&eacute;s de recibidos';
$labels['fetchmailenabled'] = 'Activo';
$labels['nofetch'] = 'No hay Datos';
$labels['fetchmail_entries'] = 'Datos de la Cuenta';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Desea borrar esta cuenta?';
$messages['fetchmaillimitreached'] = 'Sobre el Limite';
$messages['textempty'] = 'Uno o m&aacute;s campos requeridos';
?>