<?php
$labels['acc_fetchmail'] = 'Postin nouto';
$labels['fetchmailtyp'] = 'Palvelimen tyyppi';
$labels['fetchmailserver'] = 'Palvelimen osoite';
$labels['fetchmaildelete'] = 'Poista noudetut postit etäpalvelimelta';
$labels['fetchmailenabled'] = 'Käytössä';
$labels['fetchmaildisabled'] = 'Ei käytössä';
$labels['nofetch'] = 'Etäpalvelimia ei ole saatavilla';
$labels['fetchmail_entries'] = 'Saatavilla olevat etäpalvelimet';
$messages['fetchmaildelconfirm'] = 'Oletko varma että haluat poistaa tämän etäpalvelimen?';
$messages['fetchmaillimitreached'] = 'Raja saavutettu';
$messages['textempty'] = 'Yksi tai useampi kenttä on tyhjä';
