<?php
$labels = array();
$labels['acc_fetchmail'] = 'Récupération de compte';
$labels['fetchmailtyp'] = 'Protocole';
$labels['fetchmailserver'] = 'Serveur POP3/IMAP';
$labels['fetchmaildelete'] = 'Supprimer les messages après réception';
$labels['fetchmailenabled'] = 'Activer';
$labels['nofetch'] = 'Aucune entrée disponible';
$labels['fetchmail_entries'] = 'Entrées disponibles';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Etes-vous sûr de vouloir supprimer cette entrée?';
$messages['fetchmaillimitreached'] = 'Limite atteinte';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';
?>
