<?php
$labels['acc_fetchmail'] = 'Récupération de compte';
$labels['fetchmailtyp'] = 'Protocole';
$labels['fetchmailserver'] = 'Serveur POP3/IMAP';
$labels['fetchmaildelete'] = 'Supprimer les messages après réception';
$labels['fetchmailenabled'] = 'Activé';
$labels['fetchmaildisabled'] = 'Désactivé';
$labels['nofetch'] = 'Aucune entrée disponible';
$labels['fetchmail_entries'] = 'Entrées disponibles';
$messages['fetchmaildelconfirm'] = 'Êtes-vous sur de vouloir supprimer cette adresse?';
$messages['fetchmaillimitreached'] = 'Limite atteinte';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';