<?php
$labels = array();
$labels['acc_fetchmail'] = 'Contas externas';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Servidor POP3/IMAP';
$labels['fetchmaildelete'] = 'Borrar as mensaxes do servidor logo de descargalas';
$labels['fetchmailenabled'] = 'Activo';
$labels['nofetch'] = 'Non se configurou ningunha conta';
$labels['fetchmail_entries'] = 'Contas configuradas';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Seguro que quere borrar esta conta?';
$messages['fetchmaillimitreached'] = 'Non se poden engadir máis contas';
$messages['textempty'] = 'É obrigatorio encher tódolos campos';
?>