<?php
$labels = array();
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Típus';
$labels['fetchmailserver'] = 'POP3/IMAP Szerver';
$labels['fetchmaildelete'] = 'Email-ek törlése a szerverről, miután letöltődtek';
$labels['fetchmailenabled'] = 'Engedélyezés';
$labels['nofetch'] = 'Nincsen elérhető üzenetek';
$labels['fetchmail_entries'] = 'Elérhető üzenetek';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Valóban törölni szeretné ezt a bejegyzést?';
$messages['fetchmaillimitreached'] = 'Korlát elérve';
$messages['textempty'] = 'Egy vagy több mező üres';
?>
