<?php
$labels = array();
$labels['fetchmail'] = 'Recupero posta';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Server di posta POP3/IMAP';
$labels['fetchmaildelete'] = 'Rimuovi i messaggi dal server';
$labels['fetchmailenabled'] = 'Abilitato';
$labels['nofetch'] = 'Nessun elemento configurato';
$labels['fetchmail_entries'] = 'Elementi configurati';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Confermi la cancellazione dell\'elemento selezionato?';
$messages['fetchmaillimitreached'] = 'Limite raggiunto';
$messages['textempty'] = 'Uno o più campi non sono valorizzati';
?>