<?php
$labels['acc_fetchmail'] = 'Extern E-Mailen ofruffen';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3-/IMAP-Server';
$labels['fetchmaildelete'] = 'E-Mailen nom Empfank läschen';
$labels['fetchmailenabled'] = 'Aktivéiert';
$labels['fetchmaildisabled'] = 'Net aktiv';
$labels['nofetch'] = 'Keng Elementer fonnt';
$labels['fetchmail_entries'] = 'Existéierend Konten';
$messages['fetchmaildelconfirm'] = 'Wëlls du dëse Konto wierklech läschen?';
$messages['fetchmaillimitreached'] = 'Limit erreecht';
$messages['textempty'] = 'Eent oder méi Felder sinn eidel';