<?php
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Konta veids';
$labels['fetchmailserver'] = 'POP3/IMAP serveris';
$labels['fetchmaildelete'] = 'Iespējot e-pastu dzēšanu attālinātajā serverī';
$labels['fetchmailenabled'] = 'Iespējots';
$labels['fetchmaildisabled'] = 'Atspējots';
$labels['nofetch'] = 'Ieraksti nav pieejami';
$labels['fetchmail_entries'] = 'Pieejamie ieraksti';
$messages['fetchmaildelconfirm'] = 'Vai tiešām vēlaties dzēst šo ierakstu?';
$messages['fetchmaillimitreached'] = 'Ir sasniegts ierobežojums';
$messages['textempty'] = 'Viens vai vairāki lauki ir tukši';
