<?php
$labels = array();
$labels['acc_fetchmail'] = 'Extern mailaccount';
$labels['fetchmailtyp'] = 'Type';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Mail van server verwijderen na ophalen';
$labels['fetchmailenabled'] = 'Ingeschakeld';
$labels['nofetch'] = 'Geen externe mailaccounts beschikbaar';
$labels['fetchmail_entries'] = 'Beschikbare mailaccounts';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Dit externe mailaccount verwijderen?';
$messages['fetchmaillimitreached'] = 'Limiet bereikt';
$messages['textempty'] = 'Een of meer velden zijn leeg';
?>