<?php
$labels = array();
$labels['acc_fetchmail'] = 'Pobieranie poczty';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'Serwer POP3/IMAP';
$labels['fetchmaildelete'] = 'Usun wiadomosci z serwera po pobraniu';
$labels['fetchmailenabled'] = 'Wlaczone';
$labels['nofetch'] = 'Brak dostepnych pozycji';
$labels['fetchmail_entries'] = 'Dostepne pozycje';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Jestes pewny, ze chcesz usunac ta pozycje?';
$messages['fetchmaillimitreached'] = 'Osiagnieto limit';
$messages['textempty'] = 'Jedno lub wiecej pól jest puste';
?> 