<?php
$labels['acc_fetchmail'] = 'Pobieranie poczty z zewnętrznych serwerów';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'Serwer POP3/IMAP';
$labels['fetchmaildelete'] = 'Usuń wiadomości z serwera po pobraniu';
$labels['fetchmailenabled'] = 'Aktywny';
$labels['fetchmaildisabled'] = 'Nieaktywny';
$labels['nofetch'] = 'Brak dostępnych pozycji';
$labels['fetchmail_entries'] = 'Dostępne pozycje';
$messages['fetchmaildelconfirm'] = 'Jesteś pewny, ze chcesz usunąć ta pozycje?';
$messages['fetchmaillimitreached'] = 'Osiągnięto limit';
$messages['textempty'] = 'Jedno lub wiecej pól jest puste';