<?php
$labels = array();
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Servidor POP3/IMAP';
$labels['fetchmaildelete'] = 'Deletar mensagens após o recebimento';
$labels['fetchmailenabled'] = 'Ativar';
$labels['nofetch'] = 'Sem contas disponíveis';
$labels['fetchmail_entries'] = 'Contas disponíveis';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Você confirma a remoção desta conta?';
$messages['fetchmaillimitreached'] = 'Limite Atingido';
$messages['textempty'] = 'Um ou mais campos estão em branco.';
?>