<?php
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Servidor POP3/IMAP';
$labels['fetchmaildelete'] = 'Deletar mensagens após o recebimento';
$labels['fetchmailenabled'] = 'Ativa';
$labels['fetchmaildisabled'] = 'Desativada';
$labels['nofetch'] = 'Sem contas disponíveis';
$labels['fetchmail_entries'] = 'Contas disponíveis';
$messages['fetchmaildelconfirm'] = 'Você confirma a remoção desta conta?';
$messages['fetchmaillimitreached'] = 'Limite atingido';
$messages['textempty'] = 'Um ou mais campos estão em branco.';