<?php
$labels = array();
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Tipo';
$labels['fetchmailserver'] = 'Servidor POP3/IMAP';
$labels['fetchmaildelete'] = 'Deletar mensagens apуs o recebimento';
$labels['fetchmailenabled'] = 'Ativar';
$labels['nofetch'] = 'Sem contas disponнveis';
$labels['fetchmail_entries'] = 'Contas disponнveis';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Vocк confirma a remoзгo desta conta?';
$messages['fetchmaillimitreached'] = 'Limite Atingido';
$messages['textempty'] = 'Um ou mais campos estгo em branco.';
?>