<?php
$labels['acc_fetchmail'] = 'Сборка почты';
$labels['fetchmailtyp'] = 'Протокол';
$labels['fetchmailserver'] = 'POP3/IMAP сервер';
$labels['fetchmaildelete'] = 'Удалять почту с удаленного сервера после сборки';
$labels['fetchmailenabled'] = 'Включено';
$labels['fetchmaildisabled'] = 'Отключено';
$labels['nofetch'] = 'Нет записей';
$labels['fetchmail_entries'] = 'Учетные записи';
$messages['fetchmaildelconfirm'] = 'Вы действительно хотите удалить эту запись?';
$messages['fetchmaillimitreached'] = 'Достигнуто ограничение';
$messages['textempty'] = 'Одно или несколько обязательных полей не заполнены';