<?php
$labels = array();
$labels['acc_fetchmail'] = 'сборная служба';
$labels['fetchmailtyp'] = 'тип';
$labels['fetchmailserver'] = 'POP3/IMAP сервер';
$labels['fetchmaildelete'] = 'после сборки удалить почту с удаленного сервера';
$labels['fetchmailenabled'] = 'включить';
$labels['nofetch'] = 'нет записей';
$labels['fetchmail_entries'] = 'записи';

$messages = array();
$messages['fetchmaildelconfirm'] = 'вы действительно хотите удалить эту запись?';
$messages['fetchmaillimitreached'] = 'ограничение достигнуто';
$messages['textempty'] = 'одно или несколько обязательных полей пусты';
?>