<?php
$labels['acc_fetchmail'] = 'Preberanie e-mailov';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Zmazať e-maily po prebraní';
$labels['fetchmailenabled'] = 'Aktívne';
$labels['fetchmaildisabled'] = 'Neaktívne';
$labels['nofetch'] = 'Nie sú nastavené žiadne preberania';
$labels['fetchmail_entries'] = 'Nastavené preberania e-mailov';
$messages['fetchmaildelconfirm'] = 'Ste si istí, že chcete odstrániť toto preberanie e-mailov?';
$messages['fetchmaillimitreached'] = 'Bol dosiahnutý limit počtu preberaní e-mailov';
$messages['textempty'] = 'Jedno alebo viacero polí je prázdnych';
