<?php
$labels = array();
$labels['acc_fetchmail'] = 'Pograbi pošto';
$labels['fetchmailtyp'] = 'Tip stržnika';
$labels['fetchmailserver'] = 'POP3/IMAP Strežnik';
$labels['fetchmaildelete'] = 'Zbriši sporočila po sprejemu';
$labels['fetchmailenabled'] = 'Omogoči';
$labels['nofetch'] = 'Ni nobenih zapisov';
$labels['fetchmail_entries'] = 'Možni strežniki';
$labels['enabled'] = 'Omogočen';
$labels['disabled'] = 'Izklopljen';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Ali želite izbrisati ta zapis?';
$messages['fetchmaillimitreached'] = 'Dosežen limit';
$messages['textempty'] = 'Eden ali več polj je praznih';
?>