<?php
$labels = array();
$labels['acc_fetchmail'] = 'Extern mailserver';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP-server';
$labels['fetchmaildelete'] = 'Radera mail p&aring; servern';
$labels['fetchmailenabled'] = 'Aktiverad';
$labels['nofetch'] = 'Inga servrar konfigurerade';
$labels['fetchmail_entries'] = 'Tillg&auml;ngliga servrar';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Vill du radera denna post?';
$messages['fetchmaillimitreached'] = 'Begr&auml;nsning n&aring;dd';
$messages['textempty'] = 'Ett eller flera f&auml;lt &auml;r tomma';
?>