<?php
$labels['acc_fetchmail'] = 'Extern mailserver';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP-server';
$labels['fetchmaildelete'] = 'Radera mail på servern';
$labels['fetchmailenabled'] = 'Aktiverad';
$labels['fetchmaildisabled'] = 'Deaktiverad';
$labels['nofetch'] = 'Inga servrar konfigurerade';
$labels['fetchmail_entries'] = 'Tillgängliga servrar';
$messages['fetchmaildelconfirm'] = 'Vill du radera denna post?';
$messages['fetchmaillimitreached'] = 'Begränsning nådd';
$messages['textempty'] = 'Ett eller flera fält är tomma';