<?php
$labels['acc_fetchmail'] = 'Posta Alma';
$labels['fetchmailtyp'] = 'Tip';
$labels['fetchmailserver'] = 'POP3/IMAP Sunucu';
$labels['fetchmaildelete'] = 'Postaları aldıktan sonra sil';
$labels['fetchmailenabled'] = 'Aktif';
$labels['nofetch'] = 'Öğe bulunamadı';
$labels['fetchmail_entries'] = 'Uygun öğe(ler)';
$messages['fetchmaildelconfirm'] = 'Bu öğeyi silmek istiyor musunuz?';
$messages['fetchmaillimitreached'] = 'Limit aşıldı';
$messages['textempty'] = 'Bir veya daha fazla alan boş';
