<?php
$labels['acc_fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Тип';
$labels['fetchmailserver'] = 'POP3/IMAP сервер';
$labels['fetchmaildelete'] = 'Видалити листи після отримання';
$labels['fetchmailenabled'] = 'Увімкнено';
$labels['fetchmaildisabled'] = 'Вимкнено';
$labels['nofetch'] = 'Немає записів';
$labels['fetchmail_entries'] = 'Існуючі записи';
$messages['fetchmaildelconfirm'] = 'Ви впевнені, що хочете видалити цей запис?';
$messages['fetchmaillimitreached'] = 'Досягнуто ліміту';
$messages['textempty'] = 'Одне або декілька полів є порожніми';