<?php
$labels['acc_spam'] = 'Спам защита';
$labels['policy_name'] = 'Текущ филтър';
$labels['spammove'] = 'Премести маркиранте писма в Спам';
$labels['policy_entries'] = 'Създадени филтри';
$labels['policy_tag'] = 'Tag ниво';
$labels['policy_tag2'] = 'Tag2 ниво';
$labels['policy_kill'] = 'Kill ниво';
$labels['spamnopolicies'] = 'Все още няма налични правила';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
