<?php
$labels['acc_spam'] = 'Ochrana proti spamu';
$labels['policy_name'] = 'Spamfiltrová politika';
$labels['spammove'] = 'Přesunout spamové e-maily do adresáře Junk';
$labels['policy_entries'] = 'Dostupné politiky';
$labels['policy_tag'] = 'Tag úroveň';
$labels['policy_tag2'] = 'Tag2 úroveň';
$labels['policy_kill'] = 'Kill úroveň';
$labels['spamnopolicies'] = 'Žádné dostupné politiky';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
