<?php
$labels['acc_spam'] = 'Spam beskyttelse';
$labels['policy_name'] = 'Politik';
$labels['spammove'] = 'Flyt spam-e-mails til Junk-mappen';
$labels['policy_entries'] = 'Tilgængelige politikker';
$labels['policy_tag'] = 'Tag niveau';
$labels['policy_tag2'] = 'Tag2 niveau';
$labels['policy_kill'] = 'Kill niveau';
$labels['spamnopolicies'] = 'Ingen tilgængelige politikker';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
