<?php
$labels['acc_spam'] = 'Spam protection';
$labels['policy_name'] = 'Policy';
$labels['spammove'] = 'Move spam emails to junk folder';
$labels['policy_entries'] = 'Available policies';
$labels['policy_tag'] = 'Tag level';
$labels['policy_tag2'] = 'Tag2 level';
$labels['policy_kill'] = 'Kill level';
$labels['spamnopolicies'] = 'No policies available';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
