<?php
$labels['acc_spam'] = 'Spam protection';
$labels['policy_name'] = 'Policy';
$labels['spammove'] = 'Move spam emails to junk folder';
$labels['policy_entries'] = 'Available policies';
$labels['policy_tag'] = 'Tag level';
$labels['policy_tag2'] = 'Tag2 level';
$labels['policy_kill'] = 'Kill level';
$labels['spamnopolicies'] = 'No policies available';
$labels['purge_junk_days'] = 'Purge Junk automatically after X days';
$labels['purge_trash_days'] = 'Purge Trash automatically after X days';
