<?php
$labels['acc_spam'] = 'Protección contra el spam';
$labels['policy_name'] = 'Directiva';
$labels['spammove'] = 'Mover correos de Spam al directorio Junk';
$labels['policy_entries'] = 'Directivas disponibles';
$labels['policy_tag'] = 'Nivel tag';
$labels['policy_tag2'] = 'Nivel tag2';
$labels['policy_kill'] = 'Nivel kill';
$labels['spamnopolicies'] = 'No hay directivas disponibles';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
