<?php
$labels['acc_spam'] = 'Roskapostisuojaus';
$labels['policy_name'] = 'Sääntö';
$labels['spammove'] = 'Siirrä roskapostit roskapostikansioon';
$labels['policy_entries'] = 'Saatavilla olevat säännöt';
$labels['policy_tag'] = 'Tagayksen taso';
$labels['policy_tag2'] = 'Tagayksen taso 2';
$labels['policy_kill'] = 'Poiston taso';
$labels['spamnopolicies'] = 'Ei sääntöjä saatavilla';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
