<?php
$labels['acc_spam'] = 'Protection anti-spam';
$labels['policy_name'] = 'Directives';
$labels['spammove'] = 'Mettre les pouriels dans le dossier Indésirables';
$labels['policy_entries'] = 'Directives disponibles';
$labels['policy_tag'] = 'Niveau de tag';
$labels['policy_tag2'] = 'Niveau de tag2';
$labels['policy_kill'] = 'Niveau de kill';
$labels['spamnopolicies'] = 'Pas de directives disponible';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
