<?php
$labels['acc_spam'] = 'Protection anti-spam';
$labels['policy_name'] = 'Directives';
$labels['spammove'] = 'Mettre les pouriels dans le dossier Indésirables';
$labels['policy_entries'] = 'Directives disponibles';
$labels['policy_tag'] = 'Niveau de tag';
$labels['policy_tag2'] = 'Niveau de tag2';
$labels['policy_kill'] = 'Niveau de kill';
$labels['spamnopolicies'] = 'Pas de directives disponible';