<?php
$labels['acc_spam'] = 'Protección contra spam';
$labels['policy_name'] = 'Reglas';
$labels['spammove'] = 'Mover os correos detectados como spam ao cartafol "Correo lixo"';
$labels['policy_entries'] = 'Reglas disponibles';
$labels['policy_tag'] = 'Puntuación tag';
$labels['policy_tag2'] = 'Puntuación tag2';
$labels['policy_kill'] = 'Puntuación kill';
$labels['spamnopolicies'] = 'Non se definiron reglas';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
