<?php
$labels['acc_spam'] = 'Protección contra spam';
$labels['policy_name'] = 'Reglas';
$labels['spammove'] = 'Mover os correos detectados como spam ao cartafol "Correo lixo"';
$labels['policy_entries'] = 'Reglas disponibles';
$labels['policy_greylisting'] = 'Puntuación greylisting';
$labels['policy_tag'] = 'Puntuación tag';
$labels['policy_tag2'] = 'Puntuación tag2';
$labels['policy_kill'] = 'Puntuación kill';
$labels['spamnopolicies'] = 'Non se definiron reglas';