<?php
$labels['acc_spam'] = 'Spam-védelem';
$labels['policy_name'] = 'Szabály';
$labels['spammove'] = 'Mozgassa a Kéretlen leveleket a Kéretlen levelek mappába';
$labels['policy_entries'] = 'Létező Szabályok';
$labels['policy_tag'] = 'Jelölési szint';
$labels['policy_tag2'] = 'Jelölési 2 szint';
$labels['policy_kill'] = 'Kidobási szint';
$labels['spamnopolicies'] = 'Nincsenek szabályok felvéve';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
