<?php
$labels['acc_spam'] = 'Spamschutz';
$labels['policy_name'] = 'Strategie';
$labels['spammove'] = 'Spam an de Spam-Dossier verréckelen';
$labels['policy_entries'] = 'Existéierend Strategien';
$labels['policy_tag'] = 'Tag Level';
$labels['policy_tag2'] = 'Tag2 Level';
$labels['policy_kill'] = 'Kill Level';
$labels['spamnopolicies'] = 'Et existéiere keng Strategien';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
