<?php
$labels['acc_spam'] = 'Aizsardzība pret surogātpastu';
$labels['policy_name'] = 'Surogātpastu politika';
$labels['spammove'] = 'Pārvietot surogātpastu uz nevēlamo e-pastu mapi';
$labels['policy_entries'] = 'Pieejamā surogātpastu politika';
$labels['policy_tag'] = 'Pirmais līmenis';
$labels['policy_tag2'] = 'Otrais līmenis';
$labels['policy_kill'] = 'Bloķēšanas līmenis';
$labels['spamnopolicies'] = 'Nav nevienas surogātpastu politikas';
$labels['policy_note'] = "Piezīme! Pirmais līmenis: rezultāts, lai sāktu e-pastu marķēt kā surogātpastu. Otrais līmenis: rezultāts, no kura e-pasts tiks marķēts kā surogātpasts un pārvietots uz Mēstuļu mapi. Bloķēšanas līmenis: rezultāts, no kura surogātpasts tiek bloķēts.";
