<?php
$labels['acc_spam'] = 'Spam beveiliging';
$labels['policy_name'] = 'Policy';
$labels['spammove'] = 'Verplaats spam berichten naar de junk map';
$labels['policy_entries'] = 'Beschikbare policies';
$labels['policy_tag'] = 'Tag level';
$labels['policy_tag2'] = 'Tag2 level';
$labels['policy_kill'] = 'Kill level';
$labels['spamnopolicies'] = 'Geen policies beschikbaar';
$labels['policy_note'] = "Opmerking: Tag level: Score waarbij informatieve headers worden toegevoegd aan de email, Tag2 level: Score waarboven 'spam detected' headers worden toegevoegd, meestal gaat de het bericht dan naar een Junk map, Kill level: Score waarboven het systeem het bericht volledig blokkeerd.";
