<?php
$labels['acc_spam'] = 'Spam beveiliging';
$labels['policy_name'] = 'Policy';
$labels['spammove'] = 'Verplaats spam berichten naar de junk map';
$labels['policy_entries'] = 'Beschikbare policies';
$labels['policy_tag'] = 'Tag level';
$labels['policy_tag2'] = 'Tag2 level';
$labels['policy_kill'] = 'Kill level';
$labels['spamnopolicies'] = 'Geen policies beschikbaar';
$labels['purge_junk_days'] = 'Verwijder uit de Junk map automatisch na X dagen';
$labels['purge_trash_days'] = 'Verwijder uit de Prullenbak automatisch na X dagen';
