<?php
$labels['acc_spam'] = 'Ochrona przed spamem';
$labels['policy_name'] = 'Polityka';
$labels['spammove'] = 'Przenieś listy zawierające Spam do śmieci';
$labels['policy_entries'] = 'Dostępne polityki';
$labels['policy_tag'] = 'Poziom zaznaczenia';
$labels['policy_tag2'] = 'Poziom zaznaczenia2';
$labels['policy_kill'] = 'Poziom usunięcia';
$labels['spamnopolicies'] = 'Brak dostępnych polityk';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
