<?php
$labels['acc_spam'] = 'Proteção contra Spam';
$labels['policy_name'] = 'Regra';
$labels['spammove'] = 'Mover spams para o diretório Spam';
$labels['policy_entries'] = 'Regras de Spam Disponíveis';
$labels['policy_tag'] = 'Nível de Spam Tag';
$labels['policy_tag2'] = 'Nível de Spam Tag2';
$labels['policy_kill'] = 'Level Kill';
$labels['spamnopolicies'] = 'Não existem regras definidas';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
