<?php
$labels['acc_spam'] = 'Защита от спама';
$labels['policy_name'] = 'Политика';
$labels['spammove'] = 'Перемещать новые письма, помеченные как спам, в папку Нежелательная почта';
$labels['policy_entries'] = 'Доступные политики';
$labels['policy_tag'] = 'Tag уровень';
$labels['policy_tag2'] = 'Tag2 уровень';
$labels['policy_kill'] = 'Kill уровень';
$labels['spamnopolicies'] = 'Политики не найдены';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
