<?php
$labels['acc_spam'] = 'Защита от спама';
$labels['policy_name'] = 'Политика';
$labels['spammove'] = 'Перемещать новые письма, помеченные как спам, в папку Нежелательная почта';
$labels['policy_entries'] = 'Доступные политики';
$labels['policy_tag'] = 'Tag уровень';
$labels['policy_tag2'] = 'Tag2 уровень';
$labels['policy_kill'] = 'Kill уровень';
$labels['spamnopolicies'] = 'Политики не найдены';