<?php
$labels['acc_spam'] = 'Ochrana proti spamu';
$labels['policy_name'] = 'Spamfiltrová politika';
$labels['spammove'] = 'Presunúť spamové e-maily do priečinka Junk';
$labels['policy_entries'] = 'Dostupné politiky';
$labels['policy_greylisting'] = 'Greylisting úroveň';
$labels['policy_tag'] = 'Tag úroveň';
$labels['policy_tag2'] = 'Tag2 úroveň';
$labels['policy_kill'] = 'Kill úroveň';
$labels['spamnopolicies'] = 'Žiadne dostupné politiky';
