<?php
$labels['acc_spam'] = 'Zaščita pred neželeno pošto';
$labels['policy_name'] = 'Pravilo';
$labels['spammove'] = 'Premakni neželeno pošto v mapo Smeti';
$labels['policy_entries'] = 'Razpoložljivi pristopi';
$labels['policy_tag'] = 'Nivo oznake';
$labels['policy_tag2'] = 'Nivo oznake2';
$labels['policy_kill'] = 'Nivo Uniči';
$labels['spamnopolicies'] = 'Pravila niso določena';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
