<?php
$labels['acc_spam'] = 'Spamskydd';
$labels['policy_name'] = 'Policy';
$labels['spammove'] = 'Flytta spam till spam-mappen direkt';
$labels['policy_entries'] = 'Tillgängliga regler';
$labels['policy_tag'] = 'Tagg-nivå';
$labels['policy_tag2'] = 'Tagg2-nivå';
$labels['policy_kill'] = 'Raderings-nivå';
$labels['spamnopolicies'] = 'Inga regler tillgängliga';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
