<?php
$labels['acc_spam'] = 'Захист від спаму';
$labels['policy_name'] = 'Правило';
$labels['spammove'] = 'Перемістити спам-повідомлення до Спам папки';
$labels['policy_entries'] = 'Доступні правила';
$labels['policy_tag'] = 'Рівень Tag';
$labels['policy_tag2'] = 'Рівень Tag2';
$labels['policy_kill'] = 'Рівень Kill';
$labels['spamnopolicies'] = 'Немає правил';
$labels['policy_note'] = "Note: Tag level: Score to start adding spam info headers to the email, Tag2 level: The system will add 'spam detected' headers at that score often moving it to a Junk folder, Kill level: The system will trigger spam evasive actions (e.g. blocks mail) at that level.";
