<?php
$labels = array();
$labels['acc_wblist'] = 'Черен/Бял Списък';
$labels['wblisttype'] = 'Тип';
$labels['wblistwhitelist'] = 'Бял списък';
$labels['wblistblacklist'] = 'Черен списък';
$labels['wblistpriority'] = 'Приоритет';
$labels['wblistenabled'] = 'Активна';
$labels['wblistentries'] = 'Добавени записи';
$labels['wblistnorules'] = 'Все още няма добавени записи';

$messages = array();
$messages['wblistdelconfirm'] = 'Да изтрия ли този запис?';
$messages['wblimitreached'] = 'Достигнат лимит';
$messages['textempty'] = 'Едно или повече полета са празни. Попълнете ги.';
?>
