<?php
$labels = array();
$labels['acc_wblist'] = 'Černá/Bílá listina';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Bílá listina';
$labels['wblistblacklist'] = 'Černá listina';
$labels['wblistpriority'] = 'Priorita';
$labels['wblistenabled'] = 'Aktivní';
$labels['wblistentries'] = 'Již nastavená pravidla';
$labels['wblistnorules'] = 'Neexistuje žádné pravidlo';

$messages = array();
$messages['wblistdelconfirm'] = 'Jste si jisti, že se má odstranit toto pravidlo ?';
$messages['wblimitreached'] = 'Byl dosažen max. povolený počet pravidel';
$messages['textempty'] = 'Jedno nebo více polí jsou prázdné';
?>