<?php
$labels['acc_wblist'] = 'Sort/Hvid-liste';
$labels['wblisttype'] = 'Type';
$labels['wblistwhitelist'] = 'Hvid-liste';
$labels['wblistblacklist'] = 'Sort-liste';
$labels['wblistpriority'] = 'Prioritet';
$labels['wblistenabled'] = 'Aktiveret';
$labels['wblistdisabled'] = 'Deaktiveret';
$labels['wblistentries'] = 'Tilgængelige poster';
$labels['wblistnorules'] = 'Ingen poster til rådighed';
$messages['wblistdelconfirm'] = 'Vil du slette denne post?';
$messages['wblimitreached'] = 'Begrænsning nået';
$messages['textempty'] = 'Et eller flere felter er tomme';
$messages['invalidaddress'] = 'Ugyldig e-mailadresse';