<?php
$labels = array();
$labels['acc_wblist'] = 'Schwarz/Weiß Liste';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Weiße Liste';
$labels['wblistblacklist'] = 'Schwarze Liste';
$labels['wblistpriority'] = 'Priorität';
$labels['wblistenabled'] = 'Aktivieren';
$labels['wblistentries'] = 'Vorhandene Einträge';
$labels['wblistnorules'] = 'Keine Einträge vorhanden';

$messages = array();
$messages['wblistdelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['textempty'] = 'Ein oder mehr Felder sind leer';
$messages['wblimitreached'] = 'Limit erreicht';
?>