<?php
$labels['acc_wblist'] = 'Blacklist/Whitelist';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Whitelist';
$labels['wblistblacklist'] = 'Blacklist';
$labels['wblistpriority'] = 'Priorität';
$labels['wblistenabled'] = 'Aktiviert';
$labels['wblistdisabled'] = 'Deaktiviert';
$labels['wblistentries'] = 'Vorhandene Einträge';
$labels['wblistnorules'] = 'Keine Einträge vorhanden';
$messages['wblistdelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['wblimitreached'] = 'Limit erreicht';
$messages['textempty'] = 'Eines oder mehrere Felder sind leer';
$messages['invalidaddress'] = 'Ungültige E-Mail-Adresse';