<?php
$labels['acc_wblist'] = 'Blacklist / Whitelist';
$labels['wblisttype'] = 'Type';
$labels['wblistwhitelist'] = 'Whitelist';
$labels['wblistblacklist'] = 'Blacklist';
$labels['wblistpriority'] = 'Priority';
$labels['wblistenabled'] = 'Enabled';
$labels['wblistdisabled'] = 'Disabled';
$labels['wblistentries'] = 'Available entries';
$labels['wblistnorules'] = 'No entries available';
$messages['wblistdelconfirm'] = 'Are you sure you want to delete this entry?';
$messages['wblimitreached'] = 'Limit reached';
$messages['textempty'] = 'One or more fields are empty';
$messages['invalidaddress'] = 'Invalid email address';