<?php
$labels = array();
$labels['acc_wblist'] = 'Black/White List';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'White list';
$labels['wblistblacklist'] = 'Black list';
$labels['wblistpriority'] = 'Priority';
$labels['wblistenabled'] = 'Enabled';
$labels['wblistentries'] = 'Available entries';
$labels['wblistnorules'] = 'No entries available';

$messages = array();
$messages['wblistdelconfirm'] = 'Are you sure to delete this entry?';
$messages['wblimitreached'] = 'Limit reached';
$messages['textempty'] = 'One or more fields are empty';
?>