<?php
$labels = array();
$labels['acc_wblist'] = 'Lista Blanca/Negra';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'Lista Blanca';
$labels['wblistblacklist'] = 'Lista Negra';
$labels['wblistpriority'] = 'Prioridad';
$labels['wblistenabled'] = 'Activa';
$labels['wblistentries'] = 'Entradas disponibles';
$labels['wblistnorules'] = 'No hay entradas disponibles';

$messages = array();
$messages['wblistdelconfirm'] = 'Est&aacute; seguro de eliminar esta entrada?';
$messages['wblimitreached'] = 'L&iacute;mite a sido alcanzado';
$messages['textempty'] = 'Uno o m&aacute;s campos est&aacute;n vacios';
?>