<?php
$labels = array();
$labels['acc_wblist'] = 'Lista Negra/Blanca';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'Lista blanca';
$labels['wblistblacklist'] = 'Lista negra';
$labels['wblistpriority'] = 'Prioridad';
$labels['wblistenabled'] = 'Activo';
$labels['wblistentries'] = 'Entradas definidas en las listas';
$labels['wblistnorules'] = 'No se han definido entradas';

$messages = array();
$messages['wblistdelconfirm'] = '¿Está seguro de que quiere borrar esta entrada?';
$messages['wblimitreached'] = 'No se pueden añadir más entradas';
$messages['textempty'] = 'Es necesario cubrir todos los campos';
?>