<?php
$labels['acc_wblist'] = 'Lista blanca y negra';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'Lista Blanca';
$labels['wblistblacklist'] = 'Lista Negra';
$labels['wblistpriority'] = 'Prioridad';
$labels['wblistenabled'] = 'Activa';
$labels['wblistdisabled'] = 'Inactiva';
$labels['wblistentries'] = 'Entradas disponibles';
$labels['wblistnorules'] = 'No hay entradas disponibles';
$messages['wblistdelconfirm'] = '¿Seguro que desea borrar esta entrada?';
$messages['wblimitreached'] = 'Límite a sido alcanzado';
$messages['textempty'] = 'Uno o más campos están vacios';
$messages['invalidaddress'] = 'Dirección de correo electrónico no válida';