<?php
$labels['acc_wblist'] = 'Blacklist / Whitelist';
$labels['wblisttype'] = 'Tyyppi';
$labels['wblistwhitelist'] = 'Whitelist';
$labels['wblistblacklist'] = 'Blacklist';
$labels['wblistpriority'] = 'Prioriteetti';
$labels['wblistenabled'] = 'Käytössä';
$labels['wblistdisabled'] = 'Ei käytössä';
$labels['wblistentries'] = 'Saatavilla olevat säännöt';
$labels['wblistnorules'] = 'Ei sääntöjä';
$messages['wblistdelconfirm'] = 'Haluatko poistaa tämän säännön?';
$messages['wblimitreached'] = 'Raja saavutettu';
$messages['textempty'] = 'Yksi tai useampi kenttä on tyhjä';
$messages['invalidaddress'] = 'Sähköpostiosoite ei ole kelvollinen';
