<?php
$labels = array();
$labels['acc_wblist'] = 'Liste Noire/Blanche';
$labels['wblisttype'] = 'Type';
$labels['wblistwhitelist'] = 'Liste Blanche';
$labels['wblistblacklist'] = 'Liste Noire';
$labels['wblistpriority'] = 'Priorité';
$labels['wblistenabled'] = 'Activé';
$labels['wblistentries'] = 'Listes des Adresses';
$labels['wblistnorules'] = 'Aucune Adresses';

$messages = array();
$messages['wblistdelconfirm'] = 'Etes vous sur de vouloir supprimer cette Adresse?';
$messages['wblimitreached'] = 'Vous avez atteint la limite de règles';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';
?>
