<?php
$labels['acc_wblist'] = 'Liste Noire/Blanche';
$labels['wblisttype'] = 'Type';
$labels['wblistwhitelist'] = 'Liste Blanche';
$labels['wblistblacklist'] = 'Liste Noire';
$labels['wblistpriority'] = 'Priorité';
$labels['wblistenabled'] = 'Activé';
$labels['wblistdisabled'] = 'Désactivé';
$labels['wblistentries'] = 'Listes des adresses';
$labels['wblistnorules'] = 'Aucune adresse';
$messages['wblistdelconfirm'] = 'Êtes-vous sur de vouloir supprimer cette adresse?';
$messages['wblimitreached'] = 'Vous avez atteint la limite de règles';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';
$messages['invalidaddress'] = 'Adresse email invalide';