<?php
$labels['acc_wblist'] = 'Liste d’exclusion/d’autorisation';
$labels['wblisttype'] = 'Type';
$labels['wblistwhitelist'] = 'Liste d’autorisation';
$labels['wblistblacklist'] = 'Liste d’exclusion';
$labels['wblistpriority'] = 'Priorité';
$labels['wblistenabled'] = 'Activé';
$labels['wblistdisabled'] = 'Désactivé';
$labels['wblistentries'] = 'Listes des adresses';
$labels['wblistnorules'] = 'Aucune adresse';
$messages['wblistdelconfirm'] = 'Êtes-vous sûr de vouloir supprimer cette adresse?';
$messages['wblimitreached'] = 'Vous avez atteint la limite des règles';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';
$messages['invalidaddress'] = 'Adresse e-mail invalide';
