<?php
$labels = array();
$labels['acc_wblist'] = 'Lista Branca/Negra';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'Lista branca';
$labels['wblistblacklist'] = 'Lista negra';
$labels['wblistpriority'] = 'Prioridade';
$labels['wblistenabled'] = 'Activo';
$labels['wblistentries'] = 'Entradas definidas nas listas';
$labels['wblistnorules'] = 'Non se definiron entradas';

$messages = array();
$messages['wblistdelconfirm'] = 'Seguro que quere borrar esta entrada?';
$messages['wblimitreached'] = 'Non se poden engadir máis entradas';
$messages['textempty'] = 'É obrigatorio encher tódolos campos';
?>