<?php
$labels['acc_wblist'] = 'Black/White listák';
$labels['wblisttype'] = 'Típus';
$labels['wblistwhitelist'] = 'White lista';
$labels['wblistblacklist'] = 'Black lista';
$labels['wblistpriority'] = 'Prioritás';
$labels['wblistenabled'] = 'Engedélyezve';
$labels['wblistdisabled'] = 'Tétlen';
$labels['wblistentries'] = 'Létező bejegyzések';
$labels['wblistnorules'] = 'Nincsenek bejegyzések';
$messages['wblistdelconfirm'] = 'Valóban törölni szeretné ezt a bejegyzést?';
$messages['wblimitreached'] = 'Korlát elérve';
$messages['textempty'] = 'Egy vagy több mező üres';
$messages['invalidaddress'] = 'Érvénytelen Email Cím';