<?php
$labels = array();
$labels['acc_wblist'] = 'Black/White Listák';
$labels['wblisttype'] = 'Típus';
$labels['wblistwhitelist'] = 'White lista';
$labels['wblistblacklist'] = 'Black lista';
$labels['wblistpriority'] = 'Prioritás';
$labels['wblistenabled'] = 'Engedélyezve';
$labels['wblistentries'] = 'Létező bejegyzések';
$labels['wblistnorules'] = 'Nincsenek bejegyzések';

$messages = array();
$messages['wblistdelconfirm'] = 'Valóban törölni szeretné ezt a bejegyzést?';
$messages['wblimitreached'] = 'Korlát elérve';
$messages['textempty'] = 'Egy vagy több mező üres';
?>
