<?php
$labels = array();
$labels['acc_wblist'] = 'Black/White List';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'White list (consentito)';
$labels['wblistblacklist'] = 'Black list (respinto)';
$labels['wblistpriority'] = 'Priorità';
$labels['wblistenabled'] = 'Abilitato';
$labels['wblistentries'] = 'Elenco indirizzi e-mail';
$labels['wblistnorules'] = 'Nessun indirizzo in white/black list';

$messages = array();
$messages['wblistdelconfirm'] = "Sei sicuro di rimuovere\nquesto indirizzo dalla lista?";
$messages['wblimitreached'] = 'Limite raggiunto';
$messages['textempty'] = 'Uno o più campi sono vuoti';
?>