<?php
$labels['acc_wblist'] = 'Lista nera/bianca';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'Lista bianca (consentito)';
$labels['wblistblacklist'] = 'Lista nera (respinto)';
$labels['wblistpriority'] = 'Priorità';
$labels['wblistenabled'] = 'Attivo';
$labels['wblistdisabled'] = 'Inattivo';
$labels['wblistentries'] = 'Elenco indirizzi e-mail';
$labels['wblistnorules'] = 'Nessun indirizzo in white/black list';
$messages['wblistdelconfirm'] = 'Sei sicuro di rimuovere questo indirizzo dalla lista?';
$messages['wblimitreached'] = 'Limite raggiunto';
$messages['textempty'] = 'Uno o più campi sono vuoti';
$messages['invalidaddress'] = 'Indirizzo inoltro non valido';