<?php
$labels = array();
$labels['acc_wblist'] = 'Schwaarz/Wäiss Lëscht';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Wäiss Lëscht';
$labels['wblistblacklist'] = 'Schwaarz Lëscht';
$labels['wblistpriority'] = 'Prioritéit';
$labels['wblistenabled'] = 'Aktivéieren';
$labels['wblistentries'] = 'Existréierend Elementer';
$labels['wblistnorules'] = 'Et existéiere bis elo nach keng Elementer';

$messages = array();
$messages['wblistdelconfirm'] = 'Wëlls du dëst Element wierklech läschen?';
$messages['textempty'] = 'Eent oder méi Felder sinn eidel';
$messages['wblimitreached'] = 'Limit erreecht';
?>