<?php
$labels['acc_wblist'] = 'Melnais saraksts / baltais saraksts';
$labels['wblisttype'] = 'Veids';
$labels['wblistwhitelist'] = 'Baltais saraksts';
$labels['wblistblacklist'] = 'Melnais saraksts';
$labels['wblistpriority'] = 'Prioritāte';
$labels['wblistenabled'] = 'Iespējots';
$labels['wblistdisabled'] = 'Atspējots';
$labels['wblistentries'] = 'Pieejamie ieraksti';
$labels['wblistnorules'] = 'Nav pievienots neviens ieraksts';
$messages['wblistdelconfirm'] = 'Vai tiešām vēlaties dzēst šo ierakstu?';
$messages['wblimitreached'] = 'Ir sasniegts ierobežojums';
$messages['textempty'] = 'Viens vai vairāki lauki ir tukši';
$messages['invalidaddress'] = 'Nederīga e-pasta adrese';
