<?php
$labels = array();
$labels['acc_wblist'] = 'Czarna/Biała lista';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Biała lista';
$labels['wblistblacklist'] = 'Czarna lista';
$labels['wblistpriority'] = 'Priorytet';
$labels['wblistenabled'] = 'Aktywny';
$labels['wblistentries'] = 'Dostępne wpisy';
$labels['wblistnorules'] = 'Brak wpisów';

$messages = array();
$messages['wblistdelconfirm'] = 'Jesteś pewin, że chcesz skasować ten wpis?';
$messages['wblimitreached'] = 'Osiągnięto limit';
$messages['textempty'] = 'Jeden lub więcej wpisów jest pustych';
?>
