<?php
$labels['acc_wblist'] = 'Lista negra e branca';
$labels['wblisttype'] = 'Tipo';
$labels['wblistwhitelist'] = 'Lista branca';
$labels['wblistblacklist'] = 'Lista negra';
$labels['wblistpriority'] = 'Prioridade';
$labels['wblistenabled'] = 'Ativa';
$labels['wblistdisabled'] = 'Desativada';
$labels['wblistentries'] = 'Registros disponíveis';
$labels['wblistnorules'] = 'Sem registros';
$messages['wblistdelconfirm'] = 'Você confirma a remoção desta conta?';
$messages['wblimitreached'] = 'Limite atingido';
$messages['textempty'] = 'Um ou mais campos estão em branco';
$messages['invalidaddress'] = 'Endereço de correio inválido';