<?php
$labels = array();
$labels['acc_wblist'] = 'Lista Negra/Branca';
$labels['wblisttype'] = 'Tip';
$labels['wblistwhitelist'] = 'Lista Branca';
$labels['wblistblacklist'] = 'Lista Negra';
$labels['wblistpriority'] = 'Prioridade';
$labels['wblistenabled'] = 'Ativa';
$labels['wblistentries'] = 'Registros disponíveis';
$labels['wblistnorules'] = 'Sem registros';

$messages = array();
$messages['wblistdelconfirm'] = 'Está certo de remover este registro?';
$messages['wblimitreached'] = 'Limite atingido';
$messages['textempty'] = 'Um ou mais campos estão em branco';
?>