<?php
$labels['acc_wblist'] = 'Чёрные/Белые списки';
$labels['wblisttype'] = 'Тип';
$labels['wblistwhitelist'] = 'Белый список';
$labels['wblistblacklist'] = 'Чёрный список';
$labels['wblistpriority'] = 'Приоритет';
$labels['wblistenabled'] = 'Включено';
$labels['wblistdisabled'] = 'Отключено';
$labels['wblistentries'] = 'Доступные записи';
$labels['wblistnorules'] = 'Нет доступных записей';
$messages['wblistdelconfirm'] = 'Вы уверены, чтобы хотите удалить эту запись?';
$messages['wblimitreached'] = 'Достигнуто ограничение';
$messages['textempty'] = 'Одно или несколько обязательных полей не заполнены';
$messages['invalidaddress'] = 'Неверный адрес электронной почты';