<?php
$labels['acc_wblist'] = 'Čierna/Biela listina';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Biela listina';
$labels['wblistblacklist'] = 'Čierna listina';
$labels['wblistpriority'] = 'Priorita';
$labels['wblistenabled'] = 'Aktívny';
$labels['wblistdisabled'] = 'Neaktívny';
$labels['wblistentries'] = 'Nastavené pravidlá';
$labels['wblistnorules'] = 'Neexistuje žiadne pravidlo';
$messages['wblistdelconfirm'] = 'Ste si istí, že chcete odstrániť toto pravidlo?';
$messages['wblimitreached'] = 'Bol dosiahnutý limit počtu pravidiel';
$messages['textempty'] = 'Jedno alebo viacero polí je prázdnych';
$messages['invalidaddress'] = 'Neplatná e-mail adresa';
