<?php
$labels['acc_wblist'] = 'Bela-črna lista';
$labels['wblisttype'] = 'Tip';
$labels['wblistwhitelist'] = 'Bela lista - dovoli vedno';
$labels['wblistblacklist'] = 'Črna lista - zavrzi vedno';
$labels['wblistpriority'] = 'Prioriteta';
$labels['wblistenabled'] = 'Omogočen';
$labels['wblistdisabled'] = 'Deaktivirano';
$labels['wblistentries'] = 'Aktivna pravila';
$labels['wblistnorules'] = 'Ni aktivnih pravil.';
$messages['wblistdelconfirm'] = 'Resnično želiš pobrisati izbrano pravilo?';
$messages['wblimitreached'] = 'Meja dosežena';
$messages['textempty'] = 'Eno ali več polj je praznih';
$messages['invalidaddress'] = 'Neveljaven e-poštni naslov';