<?php
$labels = array();
$labels['acc_wblist'] = 'Bela/Črna lista';
$labels['wblisttype'] = 'Tip';
$labels['wblistwhitelist'] = 'Bela lista - dovoli vedno';
$labels['wblistblacklist'] = 'Črna lista - zavrzi vedno';
$labels['wblistpriority'] = 'Prioriteta';
$labels['wblistenabled'] = 'Vključeno';
$labels['wblistentries'] = 'Aktivna pravila';
$labels['wblistnorules'] = 'Ni aktivnih pravil.';

$messages = array();
$messages['wblistdelconfirm'] = 'Resnično želiš pobrisati izbrano pravilo?';
$messages['wblimitreached'] = 'Meja dosežena';
$messages['textempty'] = 'Eno ali več polj je praznih';
?>
