<?php
$labels['acc_wblist'] = 'Tillåt/spärra e-postadresser';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Tillåt';
$labels['wblistblacklist'] = 'Spärra';
$labels['wblistpriority'] = 'Prioritet';
$labels['wblistenabled'] = 'Aktiverad';
$labels['wblistdisabled'] = 'Deaktiverad';
$labels['wblistentries'] = 'Tillgängliga poster';
$labels['wblistnorules'] = 'Inga tillgängliga poster';
$messages['wblistdelconfirm'] = 'Vill du verkligen radera adressen?';
$messages['wblimitreached'] = 'Begränsning nådd';
$messages['textempty'] = 'Ett eller flera fält är tomma';
$messages['invalidaddress'] = 'Felaktig mailadress';