<?php
$labels = array();
$labels['acc_wblist'] = 'Till&aring;t/sp&auml;rra e-post';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Till&aring;t';
$labels['wblistblacklist'] = 'Sp&auml;rra';
$labels['wblistpriority'] = 'Prioritet';
$labels['wblistenabled'] = 'Aktiverad';
$labels['wblistentries'] = 'Tillg&auml;ngliga poster';
$labels['wblistnorules'] = 'Inga tillgängliga poster';

$messages = array();
$messages['wblistdelconfirm'] = 'Vill du verkligen radera adressen?';
$messages['wblimitreached'] = 'Begr&auml;nsning n&aring;dd';
$messages['textempty'] = 'Ett eller flera f&auml;lt &auml;r tomma';
?>