<?php
$labels['acc_wblist'] = 'Чорний/Білий список';
$labels['wblisttype'] = 'Тип';
$labels['wblistwhitelist'] = 'Білий список';
$labels['wblistblacklist'] = 'Чорний список';
$labels['wblistpriority'] = 'Пріоритет';
$labels['wblistenabled'] = 'Увімкнено';
$labels['wblistdisabled'] = 'Вимкнено';
$labels['wblistentries'] = 'Існуючі записи';
$labels['wblistnorules'] = 'Немає записів';
$messages['wblistdelconfirm'] = 'Ви впевнені, що хочете видалити цей запис?';
$messages['wblimitreached'] = 'Досягнуто ліміту';
$messages['textempty'] = 'Одне або декілька полів є порожніми';
$messages['invalidaddress'] = 'Недійсна адреса електронної пошти';