<?php
$labels = array();
$labels['acc_forward'] = 'Přeposílání e-mailů';
$labels['forwardingaddress'] = 'Přeposílat na jinou e-mail adresu';
$labels['forwardingenabled'] = 'Aktivní';

$messages = array();
$messages['forwardingloop'] = 'Toto přesměrování nelze použít (sám na sebe) byla by to smyčka.';
$messages['forwardingempty'] = 'Prosím zadejte e-mail adresu pro přesměrování';
$messages['invalidaddress'] = 'Špatně zadaná e-mail adresa';
?>