<?php
$labels['acc_forward'] = 'Přeposílání e-mailů';
$labels['forwardingaddress'] = 'Přeposílat na jinou e-mail adresu';
$labels['forwardnomails'] = 'Přesměrování nenalezeno';
$labels['forward_entries'] = 'Emailová adresa';
$messages['forwardingloop'] = 'Toto přesměrování nelze použít (sám na sebe) byla by to smyčka.';
$messages['forwarddelconfirm'] = 'Jste si jisti, že chcete odstranit toto přesměrování?';
$messages['forwardingempty'] = 'Prosím zadejte e-mail adresu pro přesměrování';
$messages['invalidaddress'] = 'Špatně zadaná e-mail adresa';