<?php
$labels = array();
$labels['acc_forward'] = 'Videresendelse';
$labels['forwardingaddress'] = 'Videresendelsesadresse';
$labels['forwardingenabled'] = 'Aktiveret';
$labels['forwardnomails'] = 'Ingen videresendelsesadresse fundet';
$labels['forward_entries'] = 'E-mailadresser';

$messages = array();
$messages['forwardingloop'] = 'Denne videresendelse vil loope';
$messages['forwardingempty'] = 'Indtast venligst en videresendelsesadresse';
$messages['filterdelconfirm'] = 'Vil du virkelig slette denne videresendelse?';
$messages['invalidaddress'] = 'Ugyldig e-mailadresse';
?>
