<?php
$labels['acc_forward'] = 'Videresendelse';
$labels['forwardingaddress'] = 'Videresendelsesadresse';
$labels['forwardnomails'] = 'Ingen videresendelsesadresse fundet';
$labels['forward_entries'] = 'E-mailadresser';
$messages['forwardingloop'] = 'Denne videresendelse vil loope';
$messages['forwarddelconfirm'] = 'Vil du virkelig slette denne videresendelse?';
$messages['forwardingempty'] = 'Indtast venligst en videresendelsesadresse';
$messages['invalidaddress'] = 'Ugyldig e-mailadresse';