<?php
$labels['acc_forward'] = 'Weiterleitung';
$labels['forwardingaddress'] = 'Zieladresse';
$labels['forwardnomails'] = 'Keine Weiterleitungsadresse gefunden';
$labels['forward_entries'] = 'E-Mail-Adressen';
$messages['forwardingloop'] = 'Die Weiterleitung verursacht eine Schleife';
$messages['forwarddelconfirm'] = 'Wollen Sie diese Weiterleitung wirklich löschen?';
$messages['forwardingempty'] = 'Bitte geben Sie eine Zieladresse ein';
$messages['invalidaddress'] = 'Ungültige E-Mail-Adresse';