<?php
$labels = array();
$labels['acc_forward'] = 'Weiterleitung';
$labels['forwardingaddress'] = 'Zieladresse';
$labels['forwardingenabled'] = 'Aktivieren';
$labels['forwardnomails'] = 'Keine Weiterleitungs Adresse gefunden';
$labels['forward_entries'] = 'Email Adressen';


$messages = array();
$messages['forwardingloop'] = 'Weiterleitung verursacht eine Schleife';
$messages['filterdelconfirm'] = 'Wollen Sie diese Weiterleitung wirklich
löschen?';
$messages['forwardingempty'] = 'Bitte geben Sie eine Zieladresse ein';
$messages['invalidaddress'] = 'Ungültige Adresse';
?>