<?php
$labels = array();
$labels['acc_forward'] = 'Forwarding';
$labels['forwardingaddress'] = 'Forwarding address';
$labels['forwardnomails'] = 'No forwading address found';
$labels['forwardingenabled'] = 'Enabled';
$labels['forward_entries'] = 'Email adresses';

$messages = array();
$messages['forwardingloop'] = 'This forwarding will loop';
$messages['filterdelconfirm'] = 'Are you sure to delete this forwarding?';
$messages['forwardingempty'] = 'Please enter a forwarding address';
$messages['invalidaddress'] = 'Invalid Email Address';
?>