<?php
$labels['acc_forward'] = 'Forwarding';
$labels['forwardingaddress'] = 'Forwarding address';
$labels['forwardnomails'] = 'No forwarding address found';
$labels['forward_entries'] = 'Email addresses';
$messages['forwardingloop'] = 'This forwarding will loop';
$messages['forwarddelconfirm'] = 'Are you sure to delete this forwarding?';
$messages['forwardingempty'] = 'Please enter a forwarding address';
$messages['invalidaddress'] = 'Invalid email address';