<?php
$labels = array();
$labels['acc_forward'] = 'Reenviar';
$labels['forwardingaddress'] = 'Reenviar a';
$labels['forwardingenabled'] = 'Activo';

$messages = array();
$messages['forwardingloop'] = 'Este reenvío creará un bucle';
$messages['forwardingempty'] = 'Por favor, introduzca la dirección a la que quiere reenviar';
$messages['invalidaddress'] = 'Dirección de correo incorrecta';
?>