<?php
$labels['acc_forward'] = 'Reenvío';
$labels['forwardingaddress'] = 'Dirección de reenvios';
$labels['forwardnomails'] = 'No se encontró una dirección de reenvío';
$labels['forward_entries'] = 'Direcciones de email';
$messages['forwardingloop'] = 'Este reenvio se va a enclicar';
$messages['forwarddelconfirm'] = '¿Seguro eliminar este reenvío?';
$messages['forwardingempty'] = 'Por favor ingrese una dirección de reenvío';
$messages['invalidaddress'] = 'Dirección de correo electrónico no válida';