<?php
$labels['acc_forward'] = 'Edelleenlähetys';
$labels['forwardingaddress'] = 'Edelleenlähetysosoite';
$labels['forwardnomails'] = 'Edelleenlähetysosoitteita ei löytynyt';
$labels['forward_entries'] = 'Sähköpostiosoitteet';
$messages['forwardingloop'] = 'Tämä ohjaus loisi silmukan';
$messages['forwarddelconfirm'] = 'Haluatko poistaa tämän ohjauksen?';
$messages['forwardingempty'] = 'Ole hyvä ja anna edelleenlähetysosoite';
$messages['invalidaddress'] = 'Sähköpostiosoite ei ole kelvollinen';
