<?php
$labels['acc_forward'] = 'Transfert';
$labels['forwardingaddress'] = 'Transférer vers';
$labels['forwardnomails'] = 'Aucune adresse de transfert trouvée';
$labels['forward_entries'] = 'Adresses mail';
$messages['forwardingloop'] = 'Ce transfert est une boucle infinie';
$messages['forwarddelconfirm'] = 'Êtes-vous sûr de supprimer ce transfert?';
$messages['forwardingempty'] = 'Veuillez entrer une adresse de transfert';
$messages['invalidaddress'] = 'Adresse email invalide';