<?php
$labels['acc_forward'] = 'Reenvíos';
$labels['forwardingaddress'] = 'Reenviar a';
$labels['forwardnomails'] = 'Non se atopou ningún enderezo de reenvío';
$labels['forward_entries'] = 'Enderezos de correo electrónico';
$messages['forwardingloop'] = 'Este reenvío vai crear un bucle';
$messages['forwarddelconfirm'] = '¿Seguro de borrar este reenvío?';
$messages['forwardingempty'] = 'Por favor, introduza o enderezo ao que quere reenviar';
$messages['invalidaddress'] = 'Enderezo de correo incorrecto';