<?php
$labels['acc_forward'] = 'Továbbítás';
$labels['forwardingaddress'] = 'Továbbítandó cím';
$labels['forwardnomails'] = 'Nincs megkeresési cím';
$labels['forward_entries'] = 'Email címek';
$messages['forwardingloop'] = 'Ez a továbbítás hurokba kerül';
$messages['forwarddelconfirm'] = 'Biztosan törli ezt az átirányítást?';
$messages['forwardingempty'] = 'Kérem adja meg a tovvábbításhoz szükséges címet';
$messages['invalidaddress'] = 'Érvénytelen Email Cím';