<?php
$labels['acc_forward'] = 'Inoltro';
$labels['forwardingaddress'] = 'Indirizzo inoltro';
$labels['forwardnomails'] = 'Nessun indirizzo di inoltro trovato';
$labels['forward_entries'] = 'Indirizzi email';
$messages['forwardingloop'] = 'Indirizzo inoltro non valido (loop)';
$messages['forwarddelconfirm'] = 'Eliminare questo inoltro?';
$messages['forwardingempty'] = 'Inserire l\'indirizzo di inoltro';
$messages['invalidaddress'] = 'Indirizzo inoltro non valido';