<?php
$labels['acc_forward'] = 'Weiderleedung';
$labels['forwardingaddress'] = 'Zil-Adress';
$labels['forwardnomails'] = 'Keng Forwarding Adress fonnt';
$labels['forward_entries'] = 'E-Mail-Adressen';
$messages['forwardingloop'] = 'D\'Weiderleedung verursaacht eng Schläif';
$messages['forwarddelconfirm'] = 'Gitt Dir sécher dës Läsch ze läschen?';
$messages['forwardingempty'] = 'Gëff w.e.gl eng Zil-Adress an';
$messages['invalidaddress'] = 'Ongëlteg Adress';