<?php
$labels['acc_forward'] = 'E-pasta pārsūtīšana';
$labels['forwardingaddress'] = 'Adrese uz kuru pārsūtīt e-pastu';
$labels['forwardnomails'] = 'Nav pievienota neviena pārsūtīšanas adrese';
$labels['forward_entries'] = 'E-pasta adreses';
$messages['forwardingloop'] = 'Šī pārsūtīšana veido cilpu';
$messages['forwarddelconfirm'] = 'Vai tiešām dzēst šo pāradresāciju?';
$messages['forwardingempty'] = 'Lūdzu, ievadiet pārsūtīšanas adresi';
$messages['invalidaddress'] = 'Nederīga e-pasta adrese';
