<?php
$labels['acc_forward'] = 'Przekaż dalej';
$labels['forwardingaddress'] = 'Adres docelowy';
$labels['forwardnomails'] = 'Nie znaleziono adresu przekazania';
$labels['forward_entries'] = 'Adresy e-mail';
$messages['forwardingloop'] = 'Takie przekierowanie spowoduje zapętlenie';
$messages['forwarddelconfirm'] = 'Czy na pewno usunąć to przekierowanie?';
$messages['forwardingempty'] = 'Wpisz docelowy adres';
$messages['invalidaddress'] = 'Nieprawidłowy adres email';