<?php
$labels['acc_forward'] = 'Encaminhamento';
$labels['forwardingaddress'] = 'Endereço';
$labels['forwardnomails'] = 'Nenhum endereço de encaminhamento encontrado';
$labels['forward_entries'] = 'Endereços de e-mail';
$messages['forwardingloop'] = 'Este encaminhamento ficará em loop';
$messages['forwarddelconfirm'] = 'Tem certeza de excluir este encaminhamento?';
$messages['forwardingempty'] = 'Por favor entre com o endereço de encaminhamento';
$messages['invalidaddress'] = 'Endereço de correio inválido';