<?php
$labels['acc_forward'] = 'Пересылка почты';
$labels['forwardingaddress'] = 'Адрес пересылки';
$labels['forwardnomails'] = 'Не найдено адресов для пересылки';
$labels['forward_entries'] = 'Адреса электронной почты';
$messages['forwardingloop'] = 'Эта пересылка зацыклена';
$messages['forwarddelconfirm'] = 'Вы уверены, что хотите удалить эту пересылку?';
$messages['forwardingempty'] = 'Пожалуйста, введите адрес пересылки';
$messages['invalidaddress'] = 'Неверный адрес электронной почты';