<?php
$labels = array();
$labels['acc_forward'] = 'Пересылка почты';
$labels['forwardingaddress'] = 'Адрес пересылки';
$labels['forwardnomails'] = 'Не найдено адресов для пересылки';
$labels['forwardingenabled'] = 'Включено';
$labels['forward_entries'] = 'Адреса электронной почты';

$messages = array();
$messages['forwardingloop'] = 'Эта пересылка зацыклена';
$messages['filterdelconfirm'] = 'Вы уверены, что хотите удалить эту пересылку?';
$messages['forwardingempty'] = 'Пожалуйста, введите адрес пересылки';
$messages['invalidaddress'] = 'Неверный адрес электронной почты';
?>

