<?php
$labels['acc_forward'] = 'Preposielanie e-mailov';
$labels['forwardingaddress'] = 'Adresát preposielania';
$labels['forwardnomails'] = 'Preposielanie nenájdené';
$labels['forward_entries'] = 'Emailová adresa';
$messages['forwardingloop'] = 'Nie je možné nastaviť preposielanie samému sebe.';
$messages['forwarddelconfirm'] = 'Ste si istí, že chcete odstrániť toto preposielanie?';
$messages['forwardingempty'] = 'Prosím zadajte e-mail adresu pre preposielanie';
$messages['invalidaddress'] = 'Neplatná e-mail adresa';
