<?php
$labels['acc_forward'] = 'Posredovanje';
$labels['forwardingaddress'] = 'Naslov za posredovanje';
$labels['forwardnomails'] = 'Ne najdem naslova za posredovanje';
$labels['forward_entries'] = 'E-poštni naslovi';
$messages['forwardingloop'] = 'To posredovanje bo povzročilo zanko';
$messages['forwarddelconfirm'] = 'Ali ste prepričani, da izbrišete to posredovanje?';
$messages['forwardingempty'] = 'Vnesi naslov za posredovanje';
$messages['invalidaddress'] = 'Neveljaven e-poštni naslov';