<?php
$labels['acc_forward'] = 'Vidarebefodring';
$labels['forwardingaddress'] = 'Vidarebefodra till e-post';
$labels['forwardnomails'] = 'Ingen vidarebefordringsadress hittades';
$labels['forward_entries'] = 'Mejladresser';
$messages['forwardingloop'] = 'Denna vidarebefodring kommer att loopas';
$messages['forwarddelconfirm'] = 'Är du säker på att ta bort den här vidarebefordran?';
$messages['forwardingempty'] = 'Ange en mailadress';
$messages['invalidaddress'] = 'Felaktig mailadress';