<?php
$labels['acc_forward'] = 'Yönlendirme';
$labels['forwardingaddress'] = 'Yönlendirme adresi';
$labels['forwardnomails'] = 'Yönlendirme adresi bulunamadı';
$labels['forwardingenabled'] = 'Aktif';
$labels['forward_entries'] = 'E-Posta adresleri';
$messages['forwardingloop'] = 'Bu yönlendirme döngü içeriyor';
$messages['filterdelconfirm'] = 'Bu yönlendirmeyi silmek istiyor musunuz?';
$messages['forwardingempty'] = 'Lütfen yönlendirme adresini giriniz.';
$messages['invalidaddress'] = 'Geçersiz E-Posta adresi';
