<?php
$labels['acc_forward'] = 'Пересилання';
$labels['forwardingaddress'] = 'Aдреси пересилання';
$labels['forwardnomails'] = 'Адреса пересилання не знайдена';
$labels['forward_entries'] = 'Електронні адреси';
$messages['forwardingloop'] = 'Ця переадресація кружлятиме';
$messages['forwarddelconfirm'] = 'Ви впевнені, що хочете видалити цю переадресацію?';
$messages['forwardingempty'] = 'Будь ласка, введіть адресу для пересилання';
$messages['invalidaddress'] = 'Недійсна адреса електронної пошти';