<?php
$labels['password'] = 'Парола';
$labels['changepasswd'] = 'Промяна на парола';
$labels['curpasswd'] = 'Въведете текуща парола:';
$labels['newpasswd'] = 'Въведете нова парола:';
$labels['confpasswd'] = 'Потвърдете новата парола:';
$messages['nopassword'] = 'Въвдете нова парола.';
$messages['nocurpassword'] = 'Въведете текуща парола.';
$messages['passwordincorrect'] = 'Текущата парола е грешна.';
$messages['passwordinconsistency'] = 'Новата парола и тази за потвърждение не съвпадат.';
$messages['passwordminlength'] = 'Новата паролата е прекалено къса: Трябва да съдържа минимум %d символа.';
$messages['passwordchecknumber'] = 'Новата парола трябва да съдържа поне една цифра.';
$messages['passwordchecklower'] = 'Новата парола трябва да съдържа поне една малка буква.';
$messages['passwordcheckupper'] = 'Новата парола трябва да съдържа поне една ГОЛЯМА буква.';
$messages['passwordchecksymbol'] = 'Новата парола трябва да съдържа поне един специ@лен симол.';