<?php
$labels = array();
$labels['password'] = 'Změna hesla';
$labels['changepasswd'] = 'Change Password';
$labels['curpasswd'] = 'Stávající heslo:';
$labels['newpasswd'] = 'Nové heslo:';
$labels['confpasswd'] = 'Ověření nového hesla:';

$messages = array();
$messages['nopassword'] = 'Prosím zadejte nové heslo.';
$messages['nocurpassword'] = 'Prosím zadejte stávající heslo.';
$messages['passwordincorrect'] = 'Stávající heslo nebylo zadáno správně, zkuste to prosím znovu.';
$messages['passwordinconsistency'] = 'Nové heslo a ověření nového hesla nesouhlasí, zkuste to prosím znovu.';
$messages['passwordminlength'] = 'Heslo je příliš krátké: délka hesla musí být min. %d znaků.';
?>