<?php
$labels['password'] = 'Hesla';
$labels['changepasswd'] = 'Změna hesla';
$labels['curpasswd'] = 'Stávající heslo:';
$labels['newpasswd'] = 'Nové heslo:';
$labels['confpasswd'] = 'Ověření nového hesla:';
$messages['nopassword'] = 'Prosím zadejte nové heslo.';
$messages['nocurpassword'] = 'Prosím zadejte stávající heslo.';
$messages['passwordincorrect'] = 'Stávající heslo nebylo zadáno správně, zkuste to prosím znovu.';
$messages['passwordinconsistency'] = 'Nové heslo a ověření nového hesla nesouhlasí, zkuste to prosím znovu.';
$messages['passwordminlength'] = 'Heslo je příliš krátké: délka hesla musí být min. %d znaků.';
$messages['passwordchecknumber'] = 'Heslo musí obsahovat alespoň jedno číslo.';
$messages['passwordchecklower'] = 'Heslo musí obsahovat alespoň jedno malé písmeno.';
$messages['passwordcheckupper'] = 'Heslo musí obsahovat alespoň jedno velké písmeno.';
$messages['passwordchecksymbol'] = 'Heslo musí obsahovat alespoň jeden symbol.';