<?php
$labels['password'] = 'Adgangskode';
$labels['changepasswd'] = 'Skift adgangskode';
$labels['curpasswd'] = 'Nuværende adgangskode';
$labels['newpasswd'] = 'Ny adgangskode';
$labels['confpasswd'] = 'Bekræft ny adgangskode';
$messages['nopassword'] = 'Indtast venligst en ny adgangskode.';
$messages['nocurpassword'] = 'Indtast venligst den nuværende adgangskode.';
$messages['passwordincorrect'] = 'Nuværende adgangskode er ikke korrekt.';
$messages['passwordinconsistency'] = 'Uoverensstemmelse af adgangskoder, prøv igen.';
$messages['passwordminlength'] = 'Adgangskode for kort: %d cifre krævet.';
$messages['passwordchecknumber'] = 'Adgangskode skal indeholde mindst ét tal.';
$messages['passwordchecklower'] = 'Adgangskode skal indeholde mindst ét stort bogstav.';
$messages['passwordcheckupper'] = 'Adgangskode skal indeholde mindst ét lille bogstav.';
$messages['passwordchecksymbol'] = 'Adgangskode skal indeholde mindst ét symbol.';