<?php
$labels = array();
$labels['password'] = 'Passwort';
$labels['changepasswd'] = 'Passwort &auml;ndern';
$labels['curpasswd'] = 'Altes Passwort:';
$labels['newpasswd'] = 'Neues Passwort:';
$labels['confpasswd'] = 'Neues Passwort best&auml;tigen:';

$messages = array();
$messages['nopassword'] = 'Bitte geben Sie ein neues Passwort ein.';
$messages['nocurpassword'] = 'Bitte geben Sie Ihr altes Passwort ein.';
$messages['passwordincorrect'] = 'Das Passwort ist nicht richtig.';
$messages['passwordinconsistency'] = 'Das Passwort stimmt nich &uuml;berein. Bitte versuchen Sie es nochmal again.';
$messages['passwordminlength'] = 'Das Passwort ist zu kurz (Mindestl&auml;nge ist %d Zeichen).';
$messages['passwordchecknumber'] = 'Das Passwort muss mindestens eine Zahl enthalten.';
$messages['passwordchecklower'] = 'Das Passwort muss mindestens einen Kleinbuchstaben enthalten.';
$messages['passwordcheckupper'] = 'Das Passwort muss mindestens einen Gro&szlig;buchstaben enthalten.';
$messages['passwordchecksymbol'] = 'Das Passwort muss mindestens ein Symbol enthalten.';
?>