<?php
$labels = array();
$labels['password'] = 'Passwort';
$labels['changepasswd'] = 'Passwort &auml;ndern';
$labels['curpasswd']  = 'Altes Passwort:';
$labels['newpasswd']  = 'Neues Passwort:';
$labels['confpasswd']  = 'Neues Passwort best&auml;tigen:';

$messages = array();
$messages['nopassword'] = 'Bitte geben Sie ein neues Passwort ein.';
$messages['nocurpassword'] = 'Bitte geben Sie Ihr altes Passwort ein.';
$messages['passwordincorrect'] = 'Das Passwort ist nicht richtig.';
$messages['passwordinconsistency'] = 'Das Passwort stimmt nich &uuml;berein. Bitte versuchen Sie es nochmal again.';
$messages['internalerror'] = 'Der Server hat mehrere Datenbankeintr&auml;ge aktualisiert - Kontaktieren Sie den System Administrator.';
$messages['errorsaving'] = 'Das neue Passwort konnte nicht gespeichert werden - Kontaktieren Sie den System Administrator.';
$messages['passwordminlength'] = 'Das neue Passwort ist zu kurz (Mindestl&auml;nge ist %d Zeichen).';
?>