<?php
$labels['password'] = 'Passwort';
$labels['changepasswd'] = 'Passwort ändern';
$labels['curpasswd'] = 'Altes Passwort:';
$labels['newpasswd'] = 'Neues Passwort:';
$labels['confpasswd'] = 'Neues Passwort bestätigen:';
$messages['nopassword'] = 'Bitte geben Sie ein neues Passwort ein.';
$messages['nocurpassword'] = 'Bitte geben Sie Ihr altes Passwort ein.';
$messages['passwordincorrect'] = 'Das Passwort ist nicht richtig.';
$messages['passwordinconsistency'] = 'Die Passwörter stimmen nicht überein. Bitte versuchen Sie es nochmals.';
$messages['passwordminlength'] = 'Das Passwort ist zu kurz (Mindestlänge ist %d Zeichen).';
$messages['passwordchecknumber'] = 'Das Passwort muss mindestens eine Zahl enthalten.';
$messages['passwordchecklower'] = 'Das Passwort muss mindestens einen Kleinbuchstaben enthalten.';
$messages['passwordcheckupper'] = 'Das Passwort muss mindestens einen Großbuchstaben enthalten.';
$messages['passwordchecksymbol'] = 'Das Passwort muss mindestens ein Symbol enthalten.';