<?php
$labels['password'] = 'Password';
$labels['changepasswd'] = 'Change password';
$labels['curpasswd'] = 'Current password:';
$labels['newpasswd'] = 'New password:';
$labels['confpasswd'] = 'Confirm new password:';
$messages['nopassword'] = 'Please input a new password.';
$messages['nocurpassword'] = 'Please input the current password.';
$messages['passwordincorrect'] = 'Current password is incorrect.';
$messages['passwordinconsistency'] = 'Inconsistency of password. Please try again.';
$messages['passwordminlength'] = 'Password is too short: %d digits required.';
$messages['passwordchecknumber'] = 'Password must include at least one number.';
$messages['passwordchecklower'] = 'Password must include at least one lowercase letter.';
$messages['passwordcheckupper'] = 'Password must include at least one uppercase letter.';
$messages['passwordchecksymbol'] = 'Password must include at least one symbol.';