<?php
$labels = array();
$labels['password'] = 'Contrase&ntilde;a';
$labels['changepasswd']  = 'Cambio Contrase&ntilde;a';
$labels['curpasswd']  = 'Contrase&ntilde;a Actual';
$labels['newpasswd']  = 'Nueva Contrase&ntilde;a:';
$labels['confpasswd']  = 'Confirmaci&oacute;n de Contrase&ntilde;a:';

$messages = array();
$messages['nopassword'] = 'Favor escriba la nueva contrase&ntilde;a.';
$messages['nocurpassword'] = 'Favor escriba la contrase&ntilde;a actual.';
$messages['passwordincorrect'] = 'Contrase&ntilde;a actual esta incorrecta.';
$messages['passwordinconsistency'] = 'Inconsistencia de las contrase&ntilde;a, intente nuevamente.';
$messages['passwordminlength'] = 'La contrase&ntilde;a es muy corta: %d digitos requeridos.';
?>