<?php
$labels = array();
$labels['password'] = 'Contraseña';
$labels['changepasswd'] = 'Cambiar la contraseña';
$labels['curpasswd'] = 'Contraseña actual';
$labels['newpasswd'] = 'Contraseña nueva:';
$labels['confpasswd'] = 'Confirme la contraseña nueva:';

$messages = array();
$messages['nopassword'] = 'Por favor, escriba una contraseña nueva.';
$messages['nocurpassword'] = 'Por favor, escriba la contraseña actual.';
$messages['passwordincorrect'] = 'La contraseña actual es incorrecta.';
$messages['passwordinconsistency'] = 'Las contraseñas no coinciden. Por favor, inténtelo de nuevo.';
$messages['passwordminlength'] = 'La contraseña es demasiado corta. Debe tener, al menos, %d caracteres.';
?>