<?php
$labels['password'] = 'Contraseña';
$labels['changepasswd'] = 'Cambiar la contraseña';
$labels['curpasswd'] = 'Contraseña actual';
$labels['newpasswd'] = 'Contraseña nueva:';
$labels['confpasswd'] = 'Confirme la contraseña nueva:';
$messages['nopassword'] = 'Por favor, escriba una contraseña nueva.';
$messages['nocurpassword'] = 'Por favor, escriba la contraseña actual.';
$messages['passwordincorrect'] = 'La contraseña actual es incorrecta.';
$messages['passwordinconsistency'] = 'Las contraseñas no coinciden. Por favor, inténtelo de nuevo.';
$messages['passwordminlength'] = 'La contraseña es demasiado corta. Debe tener, al menos, %d caracteres.';
$messages['passwordchecknumber'] = 'La contraseña debe incluir al menos un número.';
$messages['passwordchecklower'] = 'La contraseña debe incluir al menos una minúscula.';
$messages['passwordcheckupper'] = 'La contraseña debe incluir al menos una mayúscula.';
$messages['passwordchecksymbol'] = 'La contraseña debe incluir al menos un símbolo.';