<?php
$labels['password'] = 'Salasana';
$labels['changepasswd'] = 'Vaihda salasana';
$labels['curpasswd'] = 'Nykyinen salasana';
$labels['newpasswd'] = 'Uusi salasana';
$labels['confpasswd'] = 'Vahvista uusi salasana';
$messages['nopassword'] = 'Ole hyvä ja anna uusi salasana';
$messages['nocurpassword'] = 'Ole hyvä ja anna nykyinen salasana';
$messages['passwordincorrect'] = 'Nykyinen salasana ei ole oikein';
$messages['passwordinconsistency'] = 'Salasanat eivät täsmää, ole hyvä ja yritä uudelleen';
$messages['passwordminlength'] = 'Salasana on liian lyhyt: vähintään %d numeroa vaaditaan';
$messages['passwordchecknumber'] = 'Salasanassa täytyy olla vähintään yksi numero';
$messages['passwordchecklower'] = 'Salasanassa täytyy olla vähintään yksi pieni kirjain';
$messages['passwordcheckupper'] = 'Salasanassa täytyy olla vähintään yksi iso kirjain';
$messages['passwordchecksymbol'] = 'Salasanassa täytyy olla vähintään yksi erikoismerkki';
