<?php
$labels = array();
$labels['password'] = 'Mot de passe';
$labels['changepasswd'] = 'Changer le mot de passe';
$labels['curpasswd'] = 'Mot de passe actuel:';
$labels['newpasswd'] = 'Nouveau mot de passe:';
$labels['confpasswd'] = 'Confirmer le mot de passe:';

$messages = array();
$messages['nopassword'] = 'Merci de saisir le nouveau mot de passe.';
$messages['nocurpassword'] = 'Merci de saisir votre mot de passe actuel.';
$messages['passwordincorrect'] = 'Le mot de passe actuel est incorrect.';
$messages['passwordinconsistency'] = 'Les mots de passe ne sont pas identiques, veuillez réessayer';
$messages['passwordminlength'] = 'Le mot de passe est trop court: %d caractères requis.';
?>