<?php
$labels['password'] = 'Contrasinal';
$labels['changepasswd'] = 'Cambiar o contrasinal';
$labels['curpasswd'] = 'Contrasinal actual:';
$labels['newpasswd'] = 'Contrasinal novo:';
$labels['confpasswd'] = 'Confirme o contrasinal novo:';
$messages['nopassword'] = 'Por favor, introduza un contrasinal novo.';
$messages['nocurpassword'] = 'Por favor, introduza o contrasinal actual.';
$messages['passwordincorrect'] = 'O contrasinal actual é incorrecto.';
$messages['passwordinconsistency'] = 'Os contrasinais non coinciden. Por favor, introdúzaos de novo.';
$messages['passwordminlength'] = 'O contrasinal é curto de máis. Debe de ter, polo menos, %d caracteres.';
$messages['passwordchecknumber'] = 'O contrasinal debe incluír polo menos un número.';
$messages['passwordchecklower'] = 'O contrasinal debe incluír polo menos unha minúscula.';
$messages['passwordcheckupper'] = 'O contrasinal debe incluír polo menos unha maiúscula.';
$messages['passwordchecksymbol'] = 'O contrasinal debe incluir polo menos un símbolo.';