<?php
$labels = array();
$labels['password'] = 'Jelszó';
$labels['changepasswd']  = 'Jelszó megváltoztatása';
$labels['curpasswd']  = 'Jelenlegi Jelszó:';
$labels['newpasswd']  = 'Új Jelszó:';
$labels['confpasswd']  = 'Új Jelszó megerősítése:';

$messages = array();
$messages['nopassword'] = 'Kérem adja meg az új jelszót.';
$messages['nocurpassword'] = 'Kérem adja meg a jelenlegi jelszavát.';
$messages['passwordincorrect'] = 'Jelenlegi jelszó nem megfelelő.';
$messages['passwordinconsistency'] = 'Az új jelszavak nem egyeznek, kérem próbálja meg újra.';
$messages['passwordminlength'] = 'A jelszó túl rövid: %d karakter szükséges.';
?>
