<?php
$labels['password'] = 'Jelszó';
$labels['changepasswd'] = 'Jelszó megváltoztatása';
$labels['curpasswd'] = 'Jelenlegi Jelszó:';
$labels['newpasswd'] = 'Új Jelszó:';
$labels['confpasswd'] = 'Új Jelszó megerősítése:';
$messages['nopassword'] = 'Kérem, adja meg az új jelszót!';
$messages['nocurpassword'] = 'Kérem, adja meg a jelenlegi jelszavát.';
$messages['passwordincorrect'] = 'A jelenlegi jelszó nem megfelelő.';
$messages['passwordinconsistency'] = 'Az új jelszavak nem egyeznek, kérem próbálja meg újra.';
$messages['passwordminlength'] = 'A jelszó túl rövid: %d karakter szükséges.';
$messages['passwordchecknumber'] = 'A jelszónak legalább egy számot kell tartalmaznia.';
$messages['passwordchecklower'] = 'A jelszónak legalább egy kisbetűt kell tartalmaznia.';
$messages['passwordcheckupper'] = 'A jelszónak legalább egy nagybetűt kell tartalmaznia.';
$messages['passwordchecksymbol'] = 'A jelszónak legalább egy szimbólumot kell tartalmaznia.';