<?php
$labels = array();
$labels['password'] = 'Password';
$labels['changepasswd'] = 'Modifica la Password';
$labels['curpasswd'] = 'Password attuale:';
$labels['newpasswd'] = 'Nuova Password:';
$labels['confpasswd'] = 'Nuova Password (conferma):';

$messages = array();
$messages['nopassword'] = 'Prego, inserire una nuova password.';
$messages['nocurpassword'] = 'Prego, inserire la password attuale.';
$messages['passwordincorrect'] = 'La password attuale è errata.';
$messages['passwordinconsistency'] = 'Le nuova password non è stata inserita correttamente.<br>Prego, riprova.';
$messages['passwordminlength'] = 'La password inserita è troppo corta: sono richiesti almeno %d caratteri.';
$messages['passwordchecknumber'] = 'La password deve includere almeno un numero.';
$messages['passwordchecklower'] = 'La password deve includere almeno una lettera minuscola.';
$messages['passwordcheckupper'] = 'La password deve includere almeno una lettera maiuscola.';
$messages['passwordchecksymbol'] = 'La password deve includere almeno un simbolo.';
?>
