<?php
$labels['password'] = 'Password';
$labels['changepasswd'] = 'Cambiare la password';
$labels['curpasswd'] = 'Password attuale:';
$labels['newpasswd'] = 'Nuova Password:';
$labels['confpasswd'] = 'Nuova Password (conferma):';
$messages['nopassword'] = 'Prego, inserire una nuova password.';
$messages['nocurpassword'] = 'Prego, inserire la password attuale.';
$messages['passwordincorrect'] = 'La password attuale è errata.';
$messages['passwordinconsistency'] = 'Le nuova password non è stata inserita correttamente. Prego, riprova.';
$messages['passwordminlength'] = 'La password inserita è troppo corta: sono richiesti almeno %d caratteri.';
$messages['passwordchecknumber'] = 'La password deve includere almeno un numero.';
$messages['passwordchecklower'] = 'La password deve includere almeno una minuscola.';
$messages['passwordcheckupper'] = 'La password deve includere almeno una maiuscola.';
$messages['passwordchecksymbol'] = 'La password deve includere almeno un simbolo.';