<?php
$labels['password'] = 'Passwuert';
$labels['changepasswd'] = 'Passwuert änneren';
$labels['curpasswd'] = 'Aalt Passwuert:';
$labels['newpasswd'] = 'Neit Passwuert:';
$labels['confpasswd'] = 'Neit Passwuert bestätegen:';
$messages['nopassword'] = 'Gëff w.e.gl en neit Passwuert an.';
$messages['nocurpassword'] = 'Gëff w.e.gl däin aalt Passwuert an.';
$messages['passwordincorrect'] = 'D\'Passwuert ass net korrekt.';
$messages['passwordinconsistency'] = 'D\'Passwierder stëmmen net iwwerteneen. Probéier w.e.gl nach eng Kéier.';
$messages['passwordminlength'] = 'D\'Passwuert ass ze kuerz (Mindestlängt sinn %d Zeechen).';
$messages['passwordchecknumber'] = 'D\'Passwuert muss mindestens eng Zuel enthalen.';
$messages['passwordchecklower'] = 'D\'Passwuert muss mindestens ee klenge Buschtaf enthalen.';
$messages['passwordcheckupper'] = 'D\'Passwuert muss mindestens ee grousse Buschtaf enthalen.';
$messages['passwordchecksymbol'] = 'D\'Passwuert muss mindestens ee Symbol enthalen.';