<?php
$labels['password'] = 'Parole';
$labels['changepasswd'] = 'Mainīt paroli';
$labels['curpasswd'] = 'Pašreizējā parole:';
$labels['newpasswd'] = 'Jaunā parole:';
$labels['confpasswd'] = 'Ievadiet jauno paroli atkārtoti:';
$messages['nopassword'] = 'Lūdzu, ievadiet jauno paroli.';
$messages['nocurpassword'] = 'Lūdzu, ievadiet pašreizējo paroli.';
$messages['passwordincorrect'] = 'Pašreizējā parole nav pareiza.';
$messages['passwordinconsistency'] = 'Paroles neatbilstība. Lūdzu, mēģiniet vēlreiz.';
$messages['passwordminlength'] = 'Parole ir par īsu. Nepieciešamas vismaz %d rakstu zīmes.';
$messages['passwordchecknumber'] = 'Parolei jāsatur vismaz viens cipars.';
$messages['passwordchecklower'] = 'Parolei jāsatur vismaz viens mazais latīņu alfabēta burts.';
$messages['passwordcheckupper'] = 'Parolei jāsatur vismaz viens lielais latīņu alfabēta burts.';
$messages['passwordchecksymbol'] = 'Parolei jāsatur vismaz viens speciālais simbols.';
