<?php$labels = array();
$labels['password'] = 'Wachtwoord';
$labels['changepasswd']  = 'Wachtwoord veranderen';
$labels['curpasswd']  = 'Huidig wachtwoord:';
$labels['newpasswd']  = 'Nieuw wachtwoord:';
$labels['confpasswd']  = 'Bevestig nieuw wachtwoord:';
$messages = array();
$messages['nopassword'] = 'Vul a.u.b. nieuw wachtwoord in.';
$messages['nocurpassword'] = 'Vul a.u.b. het huidige wachtwoord in.';
$messages['passwordincorrect'] = 'Huidig wachtwoord is onjuist.';
$messages['passwordinconsistency'] = 'Nieuw wachtwoord komt niet overeen met controleveld.';
$messages['internalerror'] = 'De server heeft meer dan een records in de database aangepast. Dit kan negatieve gevolgen hebben voor alle gebruikers van de server. Neem contact op met de serveradministrator.';
$messages['errorsaving'] = 'Kan het nieuwe wachtwoord niet opslaan, neem contact op met de serveradministrator.';
$messages['passwordminlength'] = 'Wachtwoord is te kort: %d tekens vereist.';
?>