<?php
$labels = array();
$labels['password'] = 'Wachtwoord';
$labels['changepasswd'] = 'Wachtwoord veranderen';
$labels['curpasswd'] = 'Huidig wachtwoord:';
$labels['newpasswd'] = 'Nieuw wachtwoord:';
$labels['confpasswd'] = 'Bevestig nieuw wachtwoord:';

$messages = array();
$messages['nopassword'] = 'Vul a.u.b. nieuw wachtwoord in.';
$messages['nocurpassword'] = 'Vul a.u.b. het huidige wachtwoord in.';
$messages['passwordincorrect'] = 'Huidig wachtwoord is onjuist.';
$messages['passwordinconsistency'] = 'Nieuw wachtwoord komt niet overeen met controleveld.';
$messages['passwordminlength'] = 'Wachtwoord is te kort: %d tekens vereist.';
?>