<?php
$labels['password'] = 'Wachtwoord';
$labels['changepasswd'] = 'Wachtwoord wijzigen';
$labels['curpasswd'] = 'Huidig wachtwoord:';
$labels['newpasswd'] = 'Nieuw wachtwoord:';
$labels['confpasswd'] = 'Bevestig nieuw wachtwoord:';
$messages['nopassword'] = 'Vul a.u.b. nieuw wachtwoord in.';
$messages['nocurpassword'] = 'Vul a.u.b. het huidige wachtwoord in.';
$messages['passwordincorrect'] = 'Huidig wachtwoord is onjuist.';
$messages['passwordinconsistency'] = 'Nieuw wachtwoord komt niet overeen met controleveld.';
$messages['passwordminlength'] = 'Wachtwoord is te kort: %d tekens vereist.';
$messages['passwordchecknumber'] = 'Wachtwoord moet op zijn minst een nummer bevatten.';
$messages['passwordchecklower'] = 'Wachtwoord moet ten minste één kleine letter bevatten.';
$messages['passwordcheckupper'] = 'Wachtwoord moet minstens één hoofdletter bevatten.';
$messages['passwordchecksymbol'] = 'Wachtwoord moet ten minste één symbool bevatten.';