<?php
$labels = array();
$labels['password'] = 'Hasło';
$labels['changepasswd'] = 'Zmiana hasła';
$labels['curpasswd'] = 'Bieżące hasło:';
$labels['newpasswd'] = 'Nowe hasło:';
$labels['confpasswd'] = 'Potwierdź nowe hasło:';

$messages = array();
$messages['nopassword'] = 'Proszę wprowadzić nowe hasło.';
$messages['nocurpassword'] = 'Proszę wprowadzić biezące hasło.';
$messages['passwordincorrect'] = 'Bieżące hasło jest nieprawidłowe.';
$messages['passwordinconsistency'] = 'Niezgodność haseł, proszę wprowadzić ponownie.';
$messages['internalerror'] = 'Błąd bazy danych serwera. To może być niebezpieczne dla innych użytkowników. Proszę się skontaktować z administratorem systemu.';
$messages['errorsaving'] = 'Nie można zapisać hasła w bazie danych. Proszę się skontaktować z administratorem systemu.';
$messages['passwordminlength'] = 'Hasło jest za krótkie, wymagane jest minimum %d cyfr.';
messages['passwordchecknumber'] = 'Hasło musi zawierać conajmniej jedną cyfrę.';
$messages['passwordchecklower'] = 'Hasło musi zawierać conajmniej jedną małą literę.';
$messages['passwordcheckupper'] = 'Hasło musi zawierać conajmniej jedną wielką literę.';
$messages['passwordchecksymbol'] = 'Hasło musi zawierać przynajmniej jeden znak specjalny (jak . , - + ).';
?> 
