<?php
$labels = array();
$labels['password'] = 'Haslo';
$labels['changepasswd']  = 'Zmiana hasla';
$labels['curpasswd']  = 'Biezace haslo:';
$labels['newpasswd']  = 'Nowe haslo:';
$labels['confpasswd']  = 'Potwierdz nowe haslo:';

$messages = array();
$messages['nopassword'] = 'Prosze wprowadzic nowe haslo.';
$messages['nocurpassword'] = 'Prosze wprowadzic biezace haslo.';
$messages['passwordincorrect'] = 'Biezace haslo jest nieprawidlowe.';
$messages['passwordinconsistency'] = 'Niezgodnosc hasel, prosze wprowadzic ponownie.';
$messages['passwordminlength'] = 'Haslo jest za krótkie, wymagane jest minimum %d cyfr.';
?> 