<?php
$labels = array();
$labels['password'] = 'Senha';
$labels['changepasswd']  = 'Atualizar Senha';
$labels['curpasswd']  = 'Senha Atual:';
$labels['newpasswd']  = 'Nova Senha:';
$labels['confpasswd']  = 'Confirmaчуo de Senha:';

$messages = array();
$messages['nopassword'] = 'Por favor informe uma nova senha.';
$messages['nocurpassword'] = 'Por favor informe sua senha atual.';
$messages['passwordincorrect'] = 'Sua senha atual estс incorreta.';
$messages['passwordinconsistency'] = 'Senha inconsistente, tente novamente.';
$messages['internalerror'] = 'O servidor atualizou mais de uma linha no banco de dados. Isto pode ser ruim para todos os usuсrios. Entre em contato com seu administrador de sistema urgentemente.';
$messages['errorsaving'] = 'Nуo pude salvar sua nova senha no banco de dados. Contate seu administrador.';
$messages['passwordminlength'] = 'Sua senha esta muito curta: sуo requeridos pelo menso %d digitos.';
?>