<?php
$labels['password'] = 'Senha';
$labels['changepasswd'] = 'Mudar senha';
$labels['curpasswd'] = 'Senha atual:';
$labels['newpasswd'] = 'Nova senha:';
$labels['confpasswd'] = 'Confirmação de senha:';
$messages['nopassword'] = 'Por favor informe uma nova senha.';
$messages['nocurpassword'] = 'Por favor informe sua senha atual.';
$messages['passwordincorrect'] = 'Sua senha atual está incorreta.';
$messages['passwordinconsistency'] = 'Senha inconsistente, tente novamente.';
$messages['passwordminlength'] = 'Sua senha esta muito curta: são requeridos pelo menso %d digitos.';
$messages['passwordchecknumber'] = 'Senha tem que incluir pelo menos um número.';
$messages['passwordchecklower'] = 'Senha deve incluir pelo menos uma minúscula.';
$messages['passwordcheckupper'] = 'Senha deve incluir pelo menos uma maiúscula.';
$messages['passwordchecksymbol'] = 'Senha deve incluir pelo menos um símbolo.';