<?php
$labels = array();
$labels['password'] = 'Senha';
$labels['changepasswd'] = 'Atualizar Senha';
$labels['curpasswd'] = 'Senha Atual:';
$labels['newpasswd'] = 'Nova Senha:';
$labels['confpasswd'] = 'Confirmação de Senha:';

$messages = array();
$messages['nopassword'] = 'Por favor informe uma nova senha.';
$messages['nocurpassword'] = 'Por favor informe sua senha atual.';
$messages['passwordincorrect'] = 'Sua senha atual está incorreta.';
$messages['passwordinconsistency'] = 'Senha inconsistente, tente novamente.';
$messages['passwordminlength'] = 'Sua senha esta muito curta: são requeridos pelo menso %d digitos.';
?>