<?php
$labels = array();
$labels['password'] = 'пароль';
$labels['changepasswd'] = 'изменить пароль';
$labels['curpasswd'] = 'старый пароль:';
$labels['newpasswd'] = 'новый пароль:';
$labels['confpasswd'] = 'повторите новый пароль:';

$messages = array();
$messages['nopassword'] = 'пожалуйста задайте новый пароль.';
$messages['nocurpassword'] = 'пожалуйста задайте старый пароль.';
$messages['passwordincorrect'] = 'неправельный пароль.';
$messages['passwordinconsistency'] = 'пароли не совпадают, пожалуйста повторите.';
$messages['passwordminlength'] = 'новый пароль сильно короткий (минимум %d знаков).';
?>