<?php
$labels['password'] = 'Пароль';
$labels['changepasswd'] = 'Изменить пароль';
$labels['curpasswd'] = 'Старый пароль:';
$labels['newpasswd'] = 'Новый пароль:';
$labels['confpasswd'] = 'Повторите новый пароль:';
$messages['nopassword'] = 'Пожалуйста, введите новый пароль.';
$messages['nocurpassword'] = 'Пожалуйста, введите текущий пароль.';
$messages['passwordincorrect'] = 'Текущий пароль неверен.';
$messages['passwordinconsistency'] = 'Пароли не совпадают, пожалуйста, попробуйте еще раз.';
$messages['passwordminlength'] = 'Новый пароль слишком короткий (требуется минимум %d знаков).';
$messages['passwordchecknumber'] = 'Новый пароль должен содержать по крайней мере одну цифру.';
$messages['passwordchecklower'] = 'Новый пароль должен содержать по крайней мере одну маленькую букву.';
$messages['passwordcheckupper'] = 'Новый пароль должен содержать по крайней мере одну заглавную букву.';
$messages['passwordchecksymbol'] = 'Новый пароль должен содержать по крайней мере один спец-символ.';