<?php
$labels['password'] = 'Heslo';
$labels['changepasswd'] = 'Zmena hesla';
$labels['curpasswd'] = 'Aktuálne heslo:';
$labels['newpasswd'] = 'Nové heslo:';
$labels['confpasswd'] = 'Potvrdenie nového hesla:';
$messages['nopassword'] = 'Prosím zadajte nové heslo.';
$messages['nocurpassword'] = 'Prosím zadajte aktuálne heslo.';
$messages['passwordincorrect'] = 'Aktuálne heslo nebolo zadané správne, skúste to prosím znova.';
$messages['passwordinconsistency'] = 'Nové heslo a potvrdenie nového hesla sa nezhodujú, skúste to prosím znova.';
$messages['passwordminlength'] = 'Heslo je príliš krátke: dĺžka hesla musí byť min. %d znakov.';
$messages['passwordchecknumber'] = 'Heslo musí obsahovať aspoň jedno číslo.';
$messages['passwordchecklower'] = 'Heslo musí obsahovať aspoň jedno malé písmeno.';
$messages['passwordcheckupper'] = 'Heslo musí obsahovať aspoň jedno veľké písmeno.';
$messages['passwordchecksymbol'] = 'Heslo musí obsahovať aspoň jeden špeciálny znak.';
