<?php
$labels['password'] = 'Geslo';
$labels['changepasswd'] = 'Sprememba gesla';
$labels['curpasswd'] = 'Trenutno geslo:';
$labels['newpasswd'] = 'Novo geslo:';
$labels['confpasswd'] = 'Potrditev novega gesla:';
$messages['nopassword'] = 'Prosimo, vnesite novo geslo.';
$messages['nocurpassword'] = 'Prosimo, vnesite trenutno geslo.';
$messages['passwordincorrect'] = 'Trenutno geslo ni pravilno.';
$messages['passwordinconsistency'] = 'Gesla se ne ujemata, poizkusite znova.';
$messages['passwordminlength'] = 'Geslo je prekratko: vsaj %d znakov.';
$messages['passwordchecknumber'] = 'Geslo mora vključevati vsaj eno številko.';
$messages['passwordchecklower'] = 'Geslo mora vsebovati vsaj eno male črke.';
$messages['passwordcheckupper'] = 'Geslo mora vsebovati vsaj eno veliko črko.';
$messages['passwordchecksymbol'] = 'Geslo mora vsebovati vsaj en simbol.';