<?php
$labels = array();
$labels['password'] = 'L&ouml;senord';
$labels['changepasswd'] = '&Auml;ndra l&ouml;senord';
$labels['curpasswd'] = 'Nuvarande l&ouml;senord:';
$labels['newpasswd'] = 'Nytt l&ouml;senord:';
$labels['confpasswd'] = 'Bekr&auml;fta l&ouml;senord:';

$messages = array();
$messages['nopassword'] = 'Ange ett nytt l&ouml;senord.';
$messages['nocurpassword'] = 'Ange nuvarande l&ouml;senord.';
$messages['passwordincorrect'] = 'Nuvarande l&ouml;senord &auml;r felaktigt.';
$messages['passwordinconsistency'] = 'De nya l&ouml;senorden st&auml;mmer inte &ouml;verrens.';
$messages['passwordminlength'] = 'L&ouml;senordet &auml;r f&ouml;r kort, minst %d tecken kr&auml;vs.';
?>