<?php
$labels['password'] = 'Lösenord';
$labels['changepasswd'] = 'Ändra lösenord';
$labels['curpasswd'] = 'Nuvarande lösenord:';
$labels['newpasswd'] = 'Nytt lösenord:';
$labels['confpasswd'] = 'Bekräfta lösenord:';
$messages['nopassword'] = 'Ange ett nytt lösenord.';
$messages['nocurpassword'] = 'Ange nuvarande lösenord.';
$messages['passwordincorrect'] = 'Nuvarande lösenord är felaktigt.';
$messages['passwordinconsistency'] = 'De nya lösenorden stämmer inte överrens.';
$messages['passwordminlength'] = 'Lösenordet är för kort, minst %d tecken krävs.';
$messages['passwordchecknumber'] = 'Lösenordet måste innehålla minst ett nummer.';
$messages['passwordchecklower'] = 'Lösenordet måste innehålla minst en små bokstav.';
$messages['passwordcheckupper'] = 'Lösenordet måste innehålla minst en stor bokstav.';
$messages['passwordchecksymbol'] = 'Lösenordet måste innehålla minst en symbol.';