<?php
$labels['password'] = 'Parola';
$labels['changepasswd'] = 'Parolayı Değiştir';
$labels['curpasswd'] = 'Geçerli Parola:';
$labels['newpasswd'] = 'Yeni Parola:';
$labels['confpasswd'] = 'Yeni Parola Onay:';
$messages['nopassword'] = 'Lütfen yeni parolanızı giriniz.';
$messages['nocurpassword'] = 'Lütfen geçerli parolanızı giriniz.';
$messages['passwordincorrect'] = 'Geçerli parolanız yanlış.';
$messages['passwordinconsistency'] = 'Parolalar uyumsuz, lütfen tekrar deneyiniz.';
$messages['passwordminlength'] = 'Parola çok kısa: en az %d karakter gerekli.';
$messages['passwordchecknumber'] = 'Parola en az bir numara içermelidir.';
$messages['passwordchecklower'] = 'Parola en az bir küçük harf içermelidir.';
$messages['passwordcheckupper'] = 'Parola en az bir büyük harf içermelidir.';
$messages['passwordchecksymbol'] = 'Parola en az bir sembol içermelidir.';
