<?php
$labels['password'] = 'Пароль';
$labels['changepasswd'] = 'Змінити пароль';
$labels['curpasswd'] = 'Поточний пароль:';
$labels['newpasswd'] = 'Новий пароль:';
$labels['confpasswd'] = 'Підтвердити новий пароль:';
$messages['nopassword'] = 'Будь ласка, введіть новий пароль.';
$messages['nocurpassword'] = 'Будь ласка, введіть поточний пароль.';
$messages['passwordincorrect'] = 'Введений пароль невірний.';
$messages['passwordinconsistency'] = 'Паролі не збігаються. Будь ласка, повторіть спробу.';
$messages['passwordminlength'] = 'Пароль занадто короткий: потрібно %d цифри.';
$messages['passwordchecknumber'] = 'Пароль повинен містити принаймні один номер.';
$messages['passwordchecklower'] = 'Пароль повинен містити принаймні одну малу літеру.';
$messages['passwordcheckupper'] = 'Пароль повинен містити принаймні одну велику літеру.';
$messages['passwordchecksymbol'] = 'Пароль повинен містити принаймні один символ.';