<?php
$labels = array();
$labels['acc_fetchmail'] = 'Външни POP3/IMAP пощи';
$labels['fetchmailtyp'] = 'Протокол';
$labels['fetchmailserver'] = 'POP3/IMAP Сървър';
$labels['fetchmaildelete'] = 'Итриване на писмата след изтегляне';
$labels['fetchmailenabled'] = 'Активна';
$labels['nofetch'] = 'Все още няма добавени записи';
$labels['fetchmail_entries'] = 'Добавени акаунти';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Да изтрия ли този запис?';
$messages['fetchmaillimitreached'] = 'Достигнат лимит';
$messages['textempty'] = 'Едно или повече полета са празни. Попълнете ги.';
?>
