<?php
$labels['acc_autoreply'] = 'Автоматичен отговор';
$labels['autoreplymessage'] = 'Съобщение';
$labels['autoreplyenabled'] = 'Активно';
$labels['and'] = 'и';
$labels['autoreplystarton'] = 'Начална дата и час';
$labels['autoreplyendby'] = 'Крайна дата и час';
$messages['textempty'] = 'Моля да въведете текст за съобщение';
$messages['startdate_notfuture'] = 'Началната дата не може да е в миналото';
$messages['endate_notgreater'] = 'Трябва да укажете крайна дата и тя да е след началната дата';