<?php
$labels = array();
$labels['acc_autoreply'] = 'Automatická odpověď';
$labels['autoreplymessage'] = 'Text';
$labels['autoreplyenabled'] = 'Povolit automatický odpovídač';
$labels['and'] = 'and';
$labels['autoreplystarton'] = 'Začít od';
$labels['autoreplyendby'] = 'Skončit';

$messages = array();
$messages['textempty'] = 'Prosím napište text zprávy';
$messages['startdate_notfuture'] = 'Datum zahájení nemůže být v minulosti';
$messages['endate_notgreater'] = 'Datum ukončení musí být nastaveno a být pozdější než datum zahájení';
?>