<?php
$labels['acc_autoreply'] = 'Autosvar';
$labels['autoreplymessage'] = 'Besked';
$labels['autoreplyenabled'] = 'Aktiveret';
$labels['and'] = 'og';
$labels['autoreplystarton'] = 'Start den';
$labels['autoreplyendby'] = 'Slut den';
$messages['textempty'] = 'Indtast venligst en besked';
$messages['startdate_notfuture'] = 'Startdato kan ikke være i fortiden';
$messages['endate_notgreater'] = 'Slutdato skal indstilles og være senere end startdato';