<?php
$labels = array();
$labels['acc_autoreply'] = 'Automatische Nachricht';
$labels['autoreplymessage'] = 'Nachricht';
$labels['autoreplyenabled'] = 'Aktivieren';
$labels['and'] = 'und';
$labels['autoreplystarton'] = 'Startet am';
$labels['autoreplyendby'] = 'Endet am';

$messages = array();
$messages['textempty'] = 'Bitte Nachricht eingeben';
$messages['startdate_notfuture'] = 'Startdatum kann nicht in der Vergangenheit sein';
$messages['endate_notgreater'] = 'Enddatum muss gesetzt und später als das Startdatum sein';
?>