<?php
$labels = array();
$labels['acc_autoreply'] = 'Respuesta automática';
$labels['autoreplymessage'] = 'Mensaje';
$labels['autoreplyenabled'] = 'Activo';
$labels['and'] = 'y';
$labels['autoreplystarton'] = 'Desde el';
$labels['autoreplyendby'] = 'Hasta el';

$messages = array();
$messages['textempty'] = 'Por favor, escriba un mensaje';
$messages['startdate_notfuture'] = 'La fecha de inicio no puede estar en el pasado';
$messages['endate_notgreater'] = 'Debe espeficicar una fecha de finalización, y ésta debe ser posterior a la de inicio';
?>
