?php
$labels = array();
$labels['acc_autoreply'] = 'Autorespuesta';
$labels['autoreplymessage'] = 'Mensaje';
$labels['autoreplyenabled'] = 'Activo';
$labels['and'] = 'y';
$labels['autoreplystarton'] = 'Fecha de inicio';
$labels['autoreplyendby'] = 'Fecha de fin';

$messages = array();
$messages['textempty'] = 'Favor escriba su mensaje';
$messages['startdate_notfuture'] = 'Fecha de inicio no debe ser anterior a la fecha de finalizaci&oacute;';
$messages['endate_notgreater'] = 'Fecha de finalizaci&oacute; se debe establecer y ser posterior a la fecha de inicio';
?>