<?php
$labels['acc_autoreply'] = 'Respuesta automática';
$labels['autoreplymessage'] = 'Mensaje';
$labels['autoreplyenabled'] = 'Activo';
$labels['and'] = 'y';
$labels['autoreplystarton'] = 'Fecha de inicio';
$labels['autoreplyendby'] = 'Fecha de fin';
$messages['textempty'] = 'Por favor escriba su mensaje';
$messages['startdate_notfuture'] = 'La fecha de inicio no debe ser anterior a la fecha de finalización';
$messages['endate_notgreater'] = 'La fecha de finalización se debe establecer y debe ser posterior a la fecha de inicio';