<?php
$labels['acc_autoreply'] = 'Automaatvastus';
$labels['autoreplymessage'] = 'Teade';
$labels['autoreplyenabled'] = 'Sisselülitatud';
$labels['and'] = 'ja';
$labels['autoreplystarton'] = 'Alates';
$labels['autoreplyendby'] = 'Kuni';
$messages['textempty'] = 'Palun sisesta vastus';
$messages['startdate_notfuture'] = 'Algus aeg ei tohi olla minevikus';
$messages['endate_notgreater'] = 'Lõpu aeg peab olema määratud ja hilisem kui algus aeg';