<?php
$labels['acc_autoreply'] = 'Lomavastaaja';
$labels['autoreplymessage'] = 'Viesti';
$labels['autoreplyenabled'] = 'Käytössä';
$labels['and'] = 'ja';
$labels['autoreplystarton'] = 'Alkaa';
$labels['autoreplyendby'] = 'Loppuu';
$messages['textempty'] = 'Ole hyvä ja anna viesti';
$messages['startdate_notfuture'] = 'Aloitusaika ei voi olla historiassa';
$messages['endate_notgreater'] = 'Loppumisajan täytyy olla asetettu ja aloitusajan jälkeen';
