<?php
$labels = array();
$labels['acc_autoreply'] = 'Réponse automatique';
$labels['autoreplymessage'] = 'Message';
$labels['autoreplyenabled'] = 'Activer';
$labels['and'] = 'et';
$labels['autoreplystarton'] = 'Debut';
$labels['autoreplyendby'] = 'Fin';

$messages = array();
$messages['textempty'] = 'Merci de saisir un message';
$messages['startdate_notfuture'] = 'Start date cannot be in the past';
$messages['endate_notgreater'] = 'End date must be set and be later than start date';
?>
