<?php
$labels = array();
$labels['acc_autoreply'] = 'Réponse automatique';
$labels['autoreplymessage'] = 'Message';
$labels['autoreplyenabled'] = 'Activer';
$labels['and'] = 'et';
$labels['autoreplystarton'] = 'Début';
$labels['autoreplyendby'] = 'Fin';

$messages = array();
$messages['textempty'] = 'Merci de saisir un message';
$messages['startdate_notfuture'] = 'La date de début ne peut pas être dans le passé';
$messages['endate_notgreater'] = 'La date de fin doit être antérieure à la date de début';
?>
