<?php
$labels = array();
$labels['acc_autoreply'] = 'Resposta automática';
$labels['autoreplymessage'] = 'Mensaxe';
$labels['autoreplyenabled'] = 'Activo';
$labels['and'] = 'e';
$labels['autoreplystarton'] = 'Dende o';
$labels['autoreplyendby'] = 'Ata o';

$messages = array();
$messages['textempty'] = 'Por favor, escriba unha mensaxe';
$messages['startdate_notfuture'] = 'A data de comezo non pode estar no pasado';
$messages['endate_notgreater'] = 'Ten que especificar unha data de remate, e ten que ser posterior á de comezo';
?>
