<?php
$labels = array();
$labels['acc_autoreply'] = 'Automatikus válasz';
$labels['autoreplymessage'] = 'Üzenet';
$labels['autoreplyenabled'] = 'Engedélyezés';
$labels['and'] = 'és';
$labels['autoreplystarton'] = 'Kezdés';
$labels['autoreplyendby'] = 'Befejezés';

$messages = array();
$messages['textempty'] = 'Kérem írjon be egy üzenetet';
$messages['startdate_notfuture'] = 'Kezdési dátum nem lehet múltbeli időpont';
$messages['endate_notgreater'] = 'A befejezés időpontját be kell állítani, és későbbinek kell lennie, mint a Kezdés időpontjának';
?>
