<?php
$labels = array();
$labels['acc_autoreply'] = 'Autoreply';
$labels['autoreplymessage'] = 'Messaggio';
$labels['autoreplyenabled'] = 'Abilitato';
$labels['and'] = 'e';
$labels['autoreplystarton'] = 'Data inizio';
$labels['autoreplyendby'] = 'Data fine';

$messages = array();
$messages['textempty'] = 'Prego, Inserire un messaggio';
$messages['startdate_notfuture'] = 'La [Data inizio] non può essere nel passato';
$messages['endate_notgreater'] = 'La [Data fine] deve essere impostata ed essere successiva alla [Data inizio]';
?>