<?php
$labels['acc_autoreply'] = 'Autoreply';
$labels['autoreplymessage'] = 'Messaggio';
$labels['autoreplyenabled'] = 'Attivo';
$labels['and'] = 'e';
$labels['autoreplystarton'] = 'Data di inizio';
$labels['autoreplyendby'] = 'Data di fine';
$messages['textempty'] = 'Si richiede un messaggio';
$messages['startdate_notfuture'] = 'La data di inizio non può essere in passato';
$messages['endate_notgreater'] = 'La data di fine deve essere impostato ed essere successiva alla data di inizio';