<?php
$labels = array();
$labels['acc_autoreply'] = 'Automatesch Äntwert';
$labels['autoreplymessage'] = 'Noriicht';
$labels['autoreplyenabled'] = 'Aktivéieren';
$labels['and'] = 'an';
$labels['autoreplystarton'] = 'Start den';
$labels['autoreplyendby'] = 'Stoppt den';

$messages = array();
$messages['textempty'] = 'W.e.gl Noriicht aginn';
$messages['startdate_notfuture'] = 'De Startdatum kann net an der Vergaangenheet sinn';
$messages['endate_notgreater'] = 'Den Enddatum muss gesat a méi spéit ewéi de Startdatum sinn';
?>