<?php
$labels['acc_autoreply'] = 'E-pasta automātiskās atbildes';
$labels['autoreplymessage'] = 'Paziņojums';
$labels['autoreplyenabled'] = 'Iespējots';
$labels['and'] = 'un';
$labels['autoreplystarton'] = 'Sākuma laiks';
$labels['autoreplyendby'] = 'Beigu laiks';
$messages['textempty'] = 'Lūdzu, ievadiet paziņojumu';
$messages['startdate_notfuture'] = 'Sākuma laiks nevar būt pagātnē';
$messages['endate_notgreater'] = 'Beigu laikam jābūt iestatītam, un tam jābūt vēlākam par sākuma laiku';
