<?php
$labels['acc_autoreply'] = 'Autoodpowiedź';
$labels['autoreplymessage'] = 'Treść wiadomosci';
$labels['autoreplyenabled'] = 'Włączone';
$labels['and'] = 'i';
$labels['autoreplystarton'] = 'Początek';
$labels['autoreplyendby'] = 'Koniec';
$messages['textempty'] = 'Proszę wprowadzić treść wiadomości';
$messages['startdate_notfuture'] = 'Data rozpoczęcia nie może być w przeszłości';
$messages['endate_notgreater'] = 'Data zakończenia musi być ustawiona i być późniejsza niż data rozpoczęcia';