<?php
$labels['acc_autoreply'] = 'Autoresponder';
$labels['autoreplymessage'] = 'Mensagem';
$labels['autoreplyenabled'] = 'Ativado';
$labels['and'] = 'e';
$labels['autoreplystarton'] = 'Começa em';
$labels['autoreplyendby'] = 'Termina em';
$messages['textempty'] = 'Por favor digite uma mensagem';
$messages['startdate_notfuture'] = 'A data de início não pode estar no passado';
$messages['endate_notgreater'] = 'A data final deve ser definida e posterior à data de início';