<?php
$labels = array();
$labels['acc_autoreply'] = 'автоответ';
$labels['autoreplymessage'] = 'сообщение';
$labels['autoreplyenabled'] = 'включить';
$labels['and'] = 'и';
$labels['autoreplystarton'] = 'старт ';
$labels['autoreplyendby'] = 'конец ';

$messages = array();
$messages['textempty'] = 'пожалийста задайте сообщение';
$messages['startdate_notfuture'] = 'число запуска не может быть в прошлом';
$messages['endate_notgreater'] = 'число окончания обязательно и не может быть раньше числа запуска';
?>