<?php
$labels['acc_autoreply'] = 'Автоответ';
$labels['autoreplymessage'] = 'Сообщение';
$labels['autoreplyenabled'] = 'Включить';
$labels['and'] = 'и';
$labels['autoreplystarton'] = 'Начало';
$labels['autoreplyendby'] = 'Окончание';
$messages['textempty'] = 'Пожалуйста, введите сообщение';
$messages['startdate_notfuture'] = 'Дата начала не может быть в прошлом';
$messages['endate_notgreater'] = 'Дата окончания обязательна и не может быть раньше даты начала';