<?php
$labels['acc_autoreply'] = 'Automatická odpoveď';
$labels['autoreplymessage'] = 'Text';
$labels['autoreplyenabled'] = 'Povoliť automatický odpovedač';
$labels['and'] = 'a';
$labels['autoreplystarton'] = 'Dátum začiatku';
$labels['autoreplyendby'] = 'Dátum konca';
$messages['textempty'] = 'Prosím napíšte text správy';
$messages['startdate_notfuture'] = 'Dátum začiatku nemôže byť v minulosti';
$messages['endate_notgreater'] = 'Dátum konca musí byť nastavený a byť neskorší ako dátum začiatku';
