<?php
$labels['acc_autoreply'] = 'Odzivnik';
$labels['autoreplymessage'] = 'Sporočilo';
$labels['autoreplyenabled'] = 'Vklopljen';
$labels['and'] = 'in';
$labels['autoreplystarton'] = 'Začne';
$labels['autoreplyendby'] = 'Konča naprej';
$messages['textempty'] = 'Prosimo, vnesite sporočilo za odzivnik';
$messages['startdate_notfuture'] = 'Začetni datum ne more biti v preteklosti';
$messages['endate_notgreater'] = 'Končni datum mora biti nastavljen in pozneje od začetnega datuma';