<?php
$labels['acc_autoreply'] = 'Autosvar';
$labels['autoreplymessage'] = 'Meddelande';
$labels['autoreplyenabled'] = 'Aktiverad';
$labels['and'] = 'och';
$labels['autoreplystarton'] = 'Startdatum';
$labels['autoreplyendby'] = 'Slutdatum';
$messages['textempty'] = 'Skriv ett meddelande';
$messages['startdate_notfuture'] = 'Startdatum måste väljas och kan inte vara tidigare än idag';
$messages['endate_notgreater'] = 'Slutdatum måste väljas och m&aring;ste vara senare än startdatumet';