<?php
$labels = array();
$labels['acc_autoreply'] = 'Autosvar';
$labels['autoreplymessage'] = 'Meddelande';
$labels['autoreplyenabled'] = 'Aktiverad';
$labels['and'] = 'och';
$labels['autoreplystarton'] = 'Startdatum';
$labels['autoreplyendby'] = 'Slutdatum';

$messages = array();
$messages['textempty'] = 'Skriv ett meddelande';
$messages['startdate_notfuture'] = 'Startdatum m&aring;ste v&auml;ljas och kan inte vara tidigare &auml;n idag';
$messages['endate_notgreater'] = 'Slutdatum m&aring;ste v&auml;ljas och m&aring;ste vara senare &auml;n startdatumet';
?>