<?php
$labels['acc_autoreply'] = 'Otomatik Yanıt';
$labels['autoreplymessage'] = 'Mesaj';
$labels['autoreplyenabled'] = 'Aktif';
$labels['and'] = 've';
$labels['autoreplystarton'] = 'Başlangıç';
$labels['autoreplyendby'] = 'Bitiş';
$messages['textempty'] = 'Lütfen mesajınızı giriniz.';
$messages['startdate_notfuture'] = 'Başlangıç zamanı geçmiş zaman olamaz';
$messages['endate_notgreater'] = 'Bitiş tarihi başlangıçtan sonra olmalıdır';
