<?php
$labels = array();
$labels['acc_filter'] = 'Mailový Filter';
$labels['filtername'] = 'Název filtru';
$labels['filtersource'] = 'Source';
$labels['filtersubject'] = 'Předmět';
$labels['filterfrom'] = 'Odesílatel';
$labels['filterto'] = 'Adresát';
$labels['filtercontains'] = 'Obsahuje';
$labels['filteris'] = 'Je';
$labels['filterbegins'] = 'Začíná na';
$labels['filterends'] = 'Končí na';
$labels['filteraction'] = 'Akce';
$labels['filtermove'] = 'Přesunout do';
$labels['filterdelete'] = 'Smazat';
$labels['filterenabled'] = 'Aktivní';
$labels['filteradd'] = 'Přidat';
$labels['filternorules'] = 'Neexistuje žádné pravidlo';
$labels['filter_entries'] = 'Již nastavená pravidla';

$messages = array();
$messages['filterdelconfirm'] = 'Jste si jisti, že se má odstranit toto pravidlo ?';
$messages['filterlimitreached'] = 'Byl dosažen max. povolený počet pravidel';
$messages['textempty'] = 'Jedno nebo více polí jsou prázdné';
?>