<?php
$labels = array();
$labels['acc_filter'] = 'Mailfilter';
$labels['filtername'] = 'Navn';
$labels['filtersource'] = 'Kilde';
$labels['filtersubject'] = 'Emne';
$labels['filterfrom'] = 'Fra';
$labels['filterto'] = 'Til';
$labels['filtercontains'] = 'Indeholder';
$labels['filteris'] = 'Er';
$labels['filterbegins'] = 'Begynder';
$labels['filterends'] = 'Slutter';
$labels['filteraction'] = 'Handling';
$labels['filtermove'] = 'Flyt';
$labels['filterdelete'] = 'Slet';
$labels['filterenabled'] = 'Aktiveret';
$labels['filteradd'] = 'Tilføj';
$labels['filternorules'] = 'Der er ingen eksisterende regler';
$labels['filter_entries'] = 'Regler';

$messages = array();
$messages['filterdelconfirm'] = 'Vil du slette denne regel?';
$messages['filterlimitreached'] = 'Begrænsning nået';
$messages['textempty'] = 'Et eller flere felter er tomme';
?>
