<?php
$labels = array();
$labels['acc_wblist'] = 'Schwarz/Wei&szlig; Liste';
$labels['wblisttype'] = 'Typ';
$labels['wblistwhitelist'] = 'Wei&szlig;e Liste';
$labels['wblistblacklist'] = 'Schwarze Liste';
$labels['wblistpriority'] = 'Priorit&auml;t';
$labels['wblistenabled'] = 'Aktivieren';
$labels['wblistentries'] = 'Vorhandene Eintr&auml;ge';
$labels['wblistnorules'] = 'Keine Eintr&auml;ge vorhanden';

$messages = array();
$messages['wblistdelconfirm'] = 'Wollen Sie diesen Eintrag wirklich l&ouml;schen?';
$messages['textempty'] = 'Ein oder mehr Felder sind leer';
$messages['wblimitreached'] = 'Limit erreicht';
?>