<?php
$labels = array();
$labels['acc_filter'] = 'Mail Filter';
$labels['filtername'] = 'Name';
$labels['filtersource'] = 'Quelle';
$labels['filtersubject'] = 'Betreff';
$labels['filterfrom'] = 'Von';
$labels['filterto'] = 'Zu';
$labels['filtercontains'] = 'Beinhaltet';
$labels['filteris'] = 'Ist';
$labels['filterbegins'] = 'Beginnt';
$labels['filterends'] = 'Endet';
$labels['filteraction'] = 'Aktion';
$labels['filtermove'] = 'Verschieben';
$labels['filterdelete'] = 'L&ouml;schen';
$labels['filterenabled'] = 'Aktivieren';
$labels['filteradd'] = 'Hinzufügen';
$labels['filternorules'] = 'Es exisitieren keine Regeln';
$labels['filter_entries'] = 'Regeln';

$messages = array();
$messages['filterdelconfirm'] = 'Wollen Sie diese Regel wirklich l&ouml;schen?';
$messages['filterlimitreached'] = 'Limit erreicht';
$messages['textempty'] = 'Ein oder mehr Felder sind leer';
?>