<?php
$labels = array();
$labels['acc_filter'] = 'Mail Filter';
$labels['filtername'] = 'Name';
$labels['filtersource'] = 'Source';
$labels['filtersubject'] = 'Subject';
$labels['filterfrom'] = 'From';
$labels['filterto'] = 'To';
$labels['filtercontains'] = 'Contains';
$labels['filteris'] = 'Is';
$labels['filterbegins'] = 'Begins';
$labels['filterends'] = 'Ends';
$labels['filteraction'] = 'Action';
$labels['filtermove'] = 'Move';
$labels['filterdelete'] = 'Delete';
$labels['filterenabled'] = 'Enabled';
$labels['filteradd'] = 'Add';
$labels['filternorules'] = 'No rules are existing';
$labels['filter_entries'] = 'Rules';

$messages = array();
$messages['filterdelconfirm'] = 'Are you sure to delete this rule?';
$messages['filterlimitreached'] = 'Limit reached';
$messages['textempty'] = 'One or more fields are empty';
?>