<?php
$labels = array();
$labels['acc_filter'] = 'Filtros de Correo';
$labels['filtername'] = 'Nombre';
$labels['filtersource'] = 'Regla';
$labels['filtersubject'] = 'Asunto';
$labels['filterfrom'] = 'De';
$labels['filterto'] = 'Para';
$labels['filtercontains'] = 'contiene';
$labels['filteris'] = 'igual a';
$labels['filterbegins'] = 'empieza con';
$labels['filterends'] = 'termina con';
$labels['filteraction'] = 'Acción';
$labels['filtermove'] = 'Mover';
$labels['filterdelete'] = 'Borrar';
$labels['filterenabled'] = 'Activo';
$labels['filteradd'] = 'Agregar';
$labels['filternorules'] = 'No se definió ningún filtro de correo';
$labels['filter_entries'] = 'Filtros';

$messages = array();
$messages['filterdelconfirm'] = '¿Está seguro de que quiere borrar este filtro?';
$messages['filterlimitreached'] = 'No es posible añadir más filtros';
$messages['textempty'] = 'Es necesario cubrir todos los campos';
?>