<?php
$labels = array();
$labels['acc_filter'] = 'Filtros de Correo';
$labels['filtername'] = 'Nombre';
$labels['filtersource'] = 'Fuente';
$labels['filtersubject'] = 'Tema';
$labels['filterfrom'] = 'De';
$labels['filterto'] = 'Para';
$labels['filtercontains'] = 'Contiene';
$labels['filteris'] = 'Es';
$labels['filterbegins'] = 'Empieza';
$labels['filterends'] = 'Termina';
$labels['filteraction'] = 'Acci&oacute;n';
$labels['filtermove'] = 'Mover';
$labels['filterdelete'] = 'Borrar';
$labels['filterenabled'] = 'Activo';
$labels['filteradd'] = 'Agregar';
$labels['filternorules'] = 'No existe ninguna regla';
$labels['filter_entries'] = 'Reglas';

$messages = array();
$messages['filterdelconfirm'] = 'Est&aacute; seguro de que quiere borrar esta regla?';
$messages['filterlimitreached'] = 'Limite m&aacute;ximo alcalzado';
$messages['textempty'] = 'Uno o m&aacute;s campos son requeridos';
?>