<?php
$labels = array();
$labels['isp_filter'] = 'Filtrage de mail';
$labels['filtername'] = 'Nom';
$labels['filtersource'] = 'Source';
$labels['filtersubject'] = 'Sujet';
$labels['filterfrom'] = 'De';
$labels['filterto'] = 'A';
$labels['filtercontains'] = 'Contiens';
$labels['filteris'] = 'Est';
$labels['filterbegins'] = 'Commence par';
$labels['filterends'] = 'Finit par';
$labels['filteraction'] = 'Action';
$labels['filtermove'] = 'Déplacer';
$labels['filterdelete'] = 'Supprimer';
$labels['filterenabled'] = 'Activé';
$labels['filteradd'] = 'Ajouter';
$labels['filternorules'] = 'Aucune règle existante';
$labels['filter_entries'] = 'Règles';

$messages = array();
$messages['filterdelconfirm'] = 'Etes-vous sûr de vouloir supprimer cette règle?';
$messages['filterlimitreached'] = 'Limite atteinte';
$messages['textempty'] = 'Un ou plusieurs champs sont vides';
?>