<?php
$labels = array();
$labels['acc_filter'] = 'Filtros de correo';
$labels['filtername'] = 'Nome';
$labels['filtersource'] = 'Regra';
$labels['filtersubject'] = 'Asunto';
$labels['filterfrom'] = 'De';
$labels['filterto'] = 'Para';
$labels['filtercontains'] = 'contén';
$labels['filteris'] = 'igual a';
$labels['filterbegins'] = 'comeza con';
$labels['filterends'] = 'remata con';
$labels['filteraction'] = 'Acción';
$labels['filtermove'] = 'Mover';
$labels['filterdelete'] = 'Borrar';
$labels['filterenabled'] = 'Activo';
$labels['filteradd'] = 'Engadir';
$labels['filternorules'] = 'Non se definiron filtros de correo';
$labels['filter_entries'] = 'Filtros';

$messages = array();
$messages['filterdelconfirm'] = 'Seguro que quere borrar este filtro?';
$messages['filterlimitreached'] = 'Non é posible engadir máis filtros';
$messages['textempty'] = 'É obrigatorio encher tódolos campos';
?>