<?php
$labels = array();
$labels['acc_filter'] = 'Levél Szűrő';
$labels['filtername'] = 'Név';
$labels['filtersource'] = 'Forrás';
$labels['filtersubject'] = 'Tárgy';
$labels['filterfrom'] = 'Küldő';
$labels['filterto'] = 'Címzett';
$labels['filtercontains'] = 'Tartalmazza';
$labels['filteris'] = 'Egyezik';
$labels['filterbegins'] = 'Kezdődik';
$labels['filterends'] = 'Végződik';
$labels['filteraction'] = 'Folyamat';
$labels['filtermove'] = 'Mozgatás';
$labels['filterdelete'] = 'Törlés';
$labels['filterenabled'] = 'Engedélyezve';
$labels['filteradd'] = 'Hozzáad';
$labels['filternorules'] = 'Nincsenek létező szabályok';
$labels['filter_entries'] = 'Szabályok';

$messages = array();
$messages['filterdelconfirm'] = 'Valóban törölni szeretné ezt a szabályt?';
$messages['filterlimitreached'] = 'Korlát elérve';
$messages['textempty'] = 'Egy vagy több mező üres';
?>
