<?php
$labels = array();
$labels['acc_filter'] = 'Filtri posta';
$labels['filtername'] = 'Nome';
$labels['filtersource'] = 'Condizione';
$labels['filtersubject'] = 'Soggetto';
$labels['filterfrom'] = 'Mittente';
$labels['filterto'] = 'Destinatario';
$labels['filtercontains'] = 'Contiene';
$labels['filteris'] = 'è';
$labels['filterbegins'] = 'Inizia con';
$labels['filterends'] = 'Termina con';
$labels['filteraction'] = 'Azione';
$labels['filtermove'] = 'Sposta nella cartella';
$labels['filterdelete'] = 'Cancella';
$labels['filterenabled'] = 'Abilitato';
$labels['filteradd'] = 'Aggiungi';
$labels['filternorules'] = 'Non è definita alcuna regola';
$labels['filter_entries'] = 'Regole definite';

$messages = array();
$messages['filterdelconfirm'] = 'Confermi la cancellazione di questa regola?';
$messages['filterlimitreached'] = 'Numero massimo di regole raggiunto';
$messages['textempty'] = 'Uno o più campi sono vuoti';
?>