<?php
$labels = array();
$labels['acc_filter'] = 'E-Mail-Filter';
$labels['filtername'] = 'Numm';
$labels['filtersource'] = 'Source';
$labels['filtersubject'] = 'Sujet';
$labels['filterfrom'] = 'Vun';
$labels['filterto'] = 'Un';
$labels['filtercontains'] = 'Enthält';
$labels['filteris'] = 'Ass gläich';
$labels['filterbegins'] = 'Fänkt u mat';
$labels['filterends'] = 'Hält op mat';
$labels['filteraction'] = 'Aktioun';
$labels['filtermove'] = 'Verréckelen';
$labels['filterdelete'] = 'Läschen';
$labels['filterenabled'] = 'Aktivéieren';
$labels['filteradd'] = 'Dobäisetzen';
$labels['filternorules'] = 'Et existéiere keng Reegelen';
$labels['filter_entries'] = 'Reegelen';

$messages = array();
$messages['filterdelconfirm'] = 'Wëlls du dës Reegel wierklech läschen?';
$messages['filterlimitreached'] = 'Limit erreecht';
$messages['textempty'] = 'Eent oder méi Felder sinn eidel';
?>