<?php
$labels = array();
$labels['acc_filter'] = 'Mail Filter';
$labels['filtername'] = 'Naam';
$labels['filtersource'] = 'Bron';
$labels['filtersubject'] = 'Onderwerp';
$labels['filterfrom'] = 'Van';
$labels['filterto'] = 'Naar';
$labels['filtercontains'] = 'Bevat';
$labels['filteris'] = 'Is';
$labels['filterbegins'] = 'Begint';
$labels['filterends'] = 'Eindigt';
$labels['filteraction'] = 'Actie';
$labels['filtermove'] = 'Verplaatsen';
$labels['filterdelete'] = 'Verwijderen';
$labels['filterenabled'] = 'Ingeschakeld';
$labels['filteradd'] = 'Toevoegen';
$labels['filternorules'] = 'Geen regels gevonden';
$labels['filter_entries'] = 'Regels';

$messages = array();
$messages['filterdelconfirm'] = 'Deze regel verwijderen?';
$messages['filterlimitreached'] = 'Limiet bereikt';
$messages['textempty'] = 'Een of meer velden zijn leeg';
?>