<?php
$labels = array();
$labels['acc_filter'] = 'Filtr poczty';
$labels['filtername'] = 'Nazwa';
$labels['filtersource'] = 'Zródlo';
$labels['filtersubject'] = 'Temat';
$labels['filterfrom'] = 'Od';
$labels['filterto'] = 'Do';
$labels['filtercontains'] = 'Zawiera';
$labels['filteris'] = 'Jest';
$labels['filterbegins'] = 'Rozpoczyna';
$labels['filterends'] = 'Konczy';
$labels['filteraction'] = 'Akcja';
$labels['filtermove'] = 'Przesun';
$labels['filterdelete'] = 'Usun';
$labels['filterenabled'] = 'Wlaczone';
$labels['filteradd'] = 'Dodaj';
$labels['filternorules'] = 'Brak regul';
$labels['filter_entries'] = 'Reguly';

$messages = array();
$messages['filterdelconfirm'] = 'Jestes pewien, ze chcesz usunac ta regule?';
$messages['filterlimitreached'] = 'Osiagnieto limit';
$messages['textempty'] = 'Jedno lub wiecej pól jesst puste';
?> 