<?php
$labels = array();
$labels['acc_filter'] = 'Filtr poczty';
$labels['filtername'] = 'Nazwa';
$labels['filtersource'] = 'Zródlo';
$labels['filtersubject'] = 'Temat';
$labels['filterfrom'] = 'Od';
$labels['filterto'] = 'Do';
$labels['filtercontains'] = 'Zawiera';
$labels['filteris'] = 'Jest';
$labels['filterbegins'] = 'Rozpoczyna';
$labels['filterends'] = 'Kończy';
$labels['filteraction'] = 'Akcja';
$labels['filtermove'] = 'Przesuń';
$labels['filterdelete'] = 'Usuń';
$labels['filterenabled'] = 'Włączone';
$labels['filteradd'] = 'Dodaj';
$labels['filternorules'] = 'Brak reguł';
$labels['filter_entries'] = 'Reguły';

$messages = array();
$messages['filterdelconfirm'] = 'Jesteś pewien, że chcesz usunąć tą regułę?';
$messages['filterlimitreached'] = 'Osiagnięto limit';
$messages['textempty'] = 'Jedno lub wiecej pól jest puste';
?> 
