<?php
$labels = array();
$labels['isp_filter'] = 'Filtro de Correio';
$labels['filtername'] = 'Nome';
$labels['filtersource'] = 'Origem';
$labels['filtersubject'] = 'Assunto';
$labels['filterfrom'] = 'De';
$labels['filterto'] = 'Para';
$labels['filtercontains'] = 'Contйm';
$labels['filteris'] = 'й';
$labels['filterbegins'] = 'Comeзa com';
$labels['filterends'] = 'Termina com';
$labels['filteraction'] = 'Aзгo';
$labels['filtermove'] = 'Mover';
$labels['filterdelete'] = 'Deletar';
$labels['filterenabled'] = 'Ativar';
$labels['filteradd'] = 'Adcionar';
$labels['filternorules'] = 'Sem regras existentes';
$labels['filter_entries'] = 'Regras';

$messages = array();
$messages['filterdelconfirm'] = 'Vocк estб certo de remover esta regra?';
$messages['filterlimitreached'] = 'Limite atingido';
$messages['textempty'] = 'Um ou mais campos estгo em branco';
?>