<?php
$labels = array();
$labels['acc_filter'] = 'фильтр';
$labels['filtername'] = 'название';
$labels['filtersource'] = 'источник';
$labels['filtersubject'] = 'тема';
$labels['filterfrom'] = 'от кого';
$labels['filterto'] = 'кому';
$labels['filtercontains'] = 'содержит';
$labels['filteris'] = 'соответствует';
$labels['filterbegins'] = 'начинается на';
$labels['filterends'] = 'заканчивается на';
$labels['filteraction'] = 'действие';
$labels['filtermove'] = 'передвинуть';
$labels['filterdelete'] = 'удалить';
$labels['filterenabled'] = 'включить';
$labels['filteradd'] = 'добавить';
$labels['filternorules'] = 'правил не существует';
$labels['filter_entries'] = 'филтры';

$messages = array();
$messages['filterdelconfirm'] = 'вы действительно хотите удалить это правило?';
$messages['filterlimitreached'] = 'ограничение достигнуто';
$messages['textempty'] = 'одно или несколько обязательных полей пусто';
?>