<?php
$labels = array();
$labels['acc_filter'] = 'Filter';
$labels['filtername'] = 'Ime';
$labels['filtersource'] = 'Polje';
$labels['filtersubject'] = 'Zadeva';
$labels['filterfrom'] = 'Od';
$labels['filterto'] = 'Za';
$labels['filtercontains'] = 'Vsebuje';
$labels['filteris'] = 'Je';
$labels['filterbegins'] = 'Se začne z';
$labels['filterends'] = 'Se konča z';
$labels['filteraction'] = 'Operacija';
$labels['filtermove'] = 'Premakni';
$labels['filterdelete'] = 'Pobriši';
$labels['filterenabled'] = 'Vključeno';
$labels['filteradd'] = 'Dodaj';
$labels['filternorules'] = 'Ne obstaja nobeno pravilo';
$labels['filter_entries'] = 'Pravila';

$messages = array();
$messages['filterdelconfirm'] = 'Ste prepričani, da ćelite pobrisati pravilo?';
$messages['filterlimitreached'] = 'Meja dosežena';
$messages['textempty'] = 'Eno ali več polj je praznih';
?>
