<?php
$labels = array();
$labels['acc_filter'] = 'Mailfilter';
$labels['filtername'] = 'Namn';
$labels['filtersource'] = 'Regel';
$labels['filtersubject'] = '&Auml;mnet';
$labels['filterfrom'] = 'Fr&aring;n';
$labels['filterto'] = 'Till';
$labels['filtercontains'] = 'inneh&aring;ller';
$labels['filteris'] = '&auml;r';
$labels['filterbegins'] = 'b&ouml;rjar med';
$labels['filterends'] = 'slutar med';
$labels['filteraction'] = 'M&aring;l';
$labels['filtermove'] = 'Flytta';
$labels['filterdelete'] = 'Radera';
$labels['filterenabled'] = 'Aktiverad';
$labels['filteradd'] = 'L&auml;gg till';
$labels['filternorules'] = 'Inga regler funna';
$labels['filter_entries'] = 'Tillg&auml;ngliga regler';

$messages = array();
$messages['filterdelconfirm'] = 'Vill du verkligen ta bort denna regel?';
$messages['filterlimitreached'] = 'Begr&auml;nsning n&aring;dd';
$messages['textempty'] = 'Ett eller flera f&auml;lt  &auml;r tomma';
?>
